### ISSUE TITLE
Pick coordinate

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODIN#10]
The user should be able to pick a coordinate directly from the map.
Selected coordinate is copied as text to the system clipboard in the coordinate display format configured in user settings.

**Discussion**: What are the use cases (i.e. the users goal) for this?

**Comment by dehmer** [comment]
If more than one coordinate should be picked at a time, it would be possible to collect coordinates in a list (right sidebar), which then can be copied as text into the clipboard.

Picked coordinates can be displayed with markers, focusing/selecting a coordinate from the list, centers map to this coordinate and/or highlights the corresponding marker.

**Comment by dehmer** [comment]
A bi-directional synchronisation between (movable) coordinate markers on the map and (editable) coordinates in the 'pick list', would make explicit 'goto coordinate' obsolete.

**Comment by ThomasHalwax** [comment]
> If more than one coordinate should be picked at a time, it would be possible to collect coordinates in a list (right sidebar), which then can be copied as text into the clipboard.
> 
> Picked coordinates can be displayed with markers, focusing/selecting a coordinate from the list, centers map to this coordinate and/or highlights the corresponding marker.

Picking multiple coordinates at a time is like creating a polyline, isn't it? Maybe we can focus on a distance measurement tool that shows it's coordinates in a pick list.

**Comment by dehmer** [comment]
@ThomasHalwax 
For me, this feature is limited to pulling one (or more) coordinates from the map to be used as text input in other applications or for documents. Editing polylines or polygons is quite similar and may also display a list of coordinates. The same applies to a measuring tool with one or more line segments.

I think, the base case for one coordinate would be enough at the moment. But thinking ahead, a generic 'view' for a coordinate list on the map (with bi-directional synchronization; map <-> view) could kill a bunch of birds with one stone: 

* pick/copy one or more coordinates
* display (add/remove) points of interest (labelled and/or tagged coordinates)
* display (add/remove) named bookmarks (center coordinate + zoom) 

Proposal: Let's KISS and limit this feature to one coordinate for now. User selects 'pick coordinate' action, cursor changes to some sort of crosshairs, user clicks on the map, coordinates text representation gets copied to clipboard, cursor goes back to normal.

**Comment by dehmer** [comment]
depends on #11

**Comment by dehmer** [comment]
Implemented the following:

* Ctrl + Shift keys switch to copy coordinate mode (crosshairs cursor)
* Clicking the map copies coordinate to clipboard (decimal latitude/longitude)
* Screen briefly flashed, a click sound is played
* Message in on-screen display (OSD) temporarily shows: Copied coordinate to clipboard

<img width="796" alt="Screenshot 2019-04-14 at 12 24 47" src="https://user-images.githubusercontent.com/322462/56091522-5d0e8b00-5eb0-11e9-80e0-4ceba899e07c.png">
