### ISSUE TITLE
Staff Comment is displayed with more than 20 letters on the map

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#100]
If you fill in a staff comment (Amplifier/Modifier field "G") by an unit, normally only 20 letters are displayed on the map.

At the moment in ODIN it is possibile to fill in a very long text in this field If you fill in a staff comment (amplifier/modifier field "G") for a unit, usually only 20 letters are displayed on the map.

At the moment it is possible in ODIN to enter a very long text in this field, which is also displayed accordingly on the map (see screenshot).

![SC_Comment to long](https://user-images.githubusercontent.com/49548300/64527019-2759bb00-d305-11e9-8132-baaeaa9f2c2a.jpg)

The display should be limited to 20 characters on the map according to the APP6 (C) or MIL-STD-2525-C specifications.

However, it should be possible in ODIN to add a longer comment to an object, which should be readable via the property field of the object.

**Comment by dehmer** [comment]
Yes, at the moment we lack formal validation of input fields. The user gets what she asks for.
Without any data exchange, that's not a problem within the system itself.
We also have to consider MIP modifier mappings, which are not always in line with the symbology standard.

Deferring this until later.
