### ISSUE TITLE
Fill in from some units isn't possible from the toogle palette

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#101]
It is not possible for all units to move them from the Toogle palette to the map with a mouse click, because the hand symbol is displayed instead of the cross symbol at the mouse pointer.

I noticed this with the following objects:

- RELAY (Unit)
- ELECTRONIC WARFARE (Unit)
- BIOLOGICAL (Events)
- CHEMICAL (Events)
- CLASS III (Supply points)
- CLASS VIII (Supply points)
- GENERAL (Supply points)
- AMMUNITION SUPPLY POINT
- ALTERNATIVE DECON SITE/POINT
- DECON SITE/POINT (UNSPECIFIED)

Also a lot of installation/facilites (e.g. CHEMICAL & BIOLOGICAL WARFARE PRODUCTION, OPEN FACILITY, FOSSIL FUEL etc.) have the same behaviour.

However, it is the case that the display is correctly enabled in some installations (e.g. ENCLOSED FACILITY, COLLEGE UNIVERSITY etc.) or suppy points (CLASS VI, CLASS II etc.).

**Comment by dehmer** [comment]
There seems to be an issue with supported geometries.
You'll also notice some message in OSD (on-screen display) in the top/center of the display: '...feature's geometry is not supported...'

I have to look into this.

**Comment by dehmer** [comment]
done.
