### ISSUE TITLE
Improve the operational condition modifiers for tactical symbols

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#102]
Currently only the static operational conditions according to MIL-STD-2525-C, TABLE III-1 are mapped in the ODIN for tactical symbols.

For the tacticians it would also be very important that the alternate symbols for operational condition modifieres would be implemented in the ODIN so that the operational readiness of the units could be seen directly on the map (e.g. by means of coloured bars below/next to the symbol according to TABLE III-2 MIL-STD-2525-C).

![SC_Table III 2 OpStatus 2525 C](https://user-images.githubusercontent.com/49548300/64529202-a43b6380-d30a-11e9-9b8d-79c5377dd75b.jpg)

**Comment by dehmer** [comment]
Sure, we can do this.
But the graphical depiction for selected item cannot show colored bars, see #93.
If this is OK for now, I will put some more color into the picture.

<img width="719" alt="Screen Shot 2019-09-09 at 15 45 33" src="https://user-images.githubusercontent.com/322462/64536434-685bca80-d319-11e9-9cb2-681414eca582.png">

**Comment by dehmer** [comment]
done.
