### ISSUE TITLE
Objects/Map behind Toogle palette and "Find"-list are visibile

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#103]
The map and the objects on it are still visible in the background, although the Toogle palette and the "Find" list have been opened in the foreground - see screenshot:

![SC Objects behind menu visible](https://user-images.githubusercontent.com/49548300/64532747-6c381e80-d312-11e9-89f7-4d7b0b81ab9c.jpg)

The legibility of the two menus will suffer as a result. Therefore, there should be no transparency once a menu window has been opened.

**Comment by dehmer** [comment]
I will change that. Thought it looked pretty cool.
But you are right: legibility before coolness.

**Comment by dehmer** [comment]
BTW: "Find"-List is called Spotlight (Search).

**Comment by dehmer** [comment]
done.
