### ISSUE TITLE
Combat units in the feature palette includes also non-combat units

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#104]
The "Combat units" section of the Toogle palette also contains "non-combat units" (e.g. Signal, Supply, Radar, Medical, Maintenance etc.).

![SC Search list combat units](https://user-images.githubusercontent.com/49548300/64533748-6e02e180-d314-11e9-8d77-fae5f46adb17.jpg)

If such a specific list is offered, it should be "pure".

Perhaps it would be possible here to offer areas, as they are also summarized in the APP 6 (C) or in the MIL-STD-2525-C.

**Comment by dehmer** [comment]
When you provide lists for each set, I'd happily change that.
Additional sets, for e.g. 'Events', 'Tasks' or similar can be added too.

**Comment by dehmer** [comment]
Feature sets are now extracted on startup-time from an Excel file in the root directory: `feature-sets.xlsx`
