### ISSUE TITLE
Jumping to new locations using spotlight makes lines and areas following you

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/ODIN#116]
I draw lines or areas (let's say in or around Vienna) and then I use Spotlight to search for a location far outside the viewport (i.e. the Karawanken in Karinthia/Slovenia) and jump to this location by using the double-click the lines and areas stay visible on the screen. When doing a manual zoom the "ghost" elements disappear.

This effect can not be observed with units and equipments.
<img width="1392" alt="Bildschirmfoto 2019-09-20 um 21 55 11" src="https://user-images.githubusercontent.com/38359572/65355202-aeeed600-dbf1-11e9-8577-ef27dcc09962.png">
<img width="1392" alt="Bildschirmfoto 2019-09-20 um 21 56 00" src="https://user-images.githubusercontent.com/38359572/65355203-aeeed600-dbf1-11e9-845b-ad8b84574c40.png">
<img width="1392" alt="Bildschirmfoto 2019-09-20 um 21 56 20" src="https://user-images.githubusercontent.com/38359572/65355204-af876c80-dbf1-11e9-9ee4-9f6b1b2423d6.png">

**Comment by dehmer** [comment]
Confirmed.
Currently, geometries only get re-projected when zoom level changes.
They must also be re-projected to pixel coordinates when the viewport changes.
This will be address when clipping of visible features is implemented, see #110.

**Comment by dehmer** [comment]
Fixed.
