### ISSUE TITLE
Feature properties for areas have duplicate controls for "hostility status"

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/ODIN#118]
The property page for areas contains a drop-down selection that contains all allowed hostility statuses as well as a checkbox element for "hostile". Whenever one checks the "hostile" checkbox the status changes as expected. But what is the expected behavior when the checkbox gets unchecked? Since this might be a source of confusion I'd recommend to remove the checkbox and use the drop-down control in order to set the hostility status of an element.

<img width="288" alt="image" src="https://user-images.githubusercontent.com/38359572/65421404-efbe3900-de03-11e9-8b93-76daef65c92a.png">

**Comment by dehmer** [comment]
This is a conscious decision. If selected 'Hostile (Enemy)' sets optional modifier N to 'ENY', which effects all features displaying this modifier. In addition standard identity is automatically updated to 'hostile'. But selecting 'hostile' standard identity will not automatically check 'Hostile (Enemy)'.
