### ISSUE TITLE
Increase contrast for symbols

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/ODIN#120]
When placing symbols on a map it can be hard to read the text modifiers. This is especially true when using a provider with ortho tiles.

By adding a outline to the symbols the readability increases substantially (see attached examples with ```outlineColor: 'white'``` and ```outlineWidth: 3```).
<img width="203" alt="image" src="https://user-images.githubusercontent.com/38359572/65596137-87539100-df96-11e9-95c8-8aabf4a5f435.png">
<img width="195" alt="image" src="https://user-images.githubusercontent.com/38359572/65596181-a520f600-df96-11e9-8c5a-05ca3c9f3444.png">
<img width="191" alt="image" src="https://user-images.githubusercontent.com/38359572/65596221-bc5fe380-df96-11e9-8efd-1bcb6462ae9e.png">

**Comment by dehmer** [comment]
Realized with introduction of uniform feature styles.
