### ISSUE TITLE
TACGRP - FOLLOW AND SUPPORT: TACGRP.TSK.FLWASS.FLWSUP

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODIN#125]

**Comment by harrywipperfuerth** [comment]
In version 0.4.1 it's possible to create the tactical graphics "Follow and Support" and "Follow and Assume" with locations on the map.

The tactical graphic is not displayed correctly on the map (only a line).

![SC_V_0_4_1 Follow and Assume](https://user-images.githubusercontent.com/49548300/66773307-09ace200-eebf-11e9-8297-c7945f2af6fb.jpg)

The correct representation according to MIL-STD-2525-C:

"Follow and Support":

![SC_V_0_4_1 Follow and Assume_2525c_2](https://user-images.githubusercontent.com/49548300/66773400-2c3efb00-eebf-11e9-8bd0-6467c7e243cf.jpg)

"Follow and Assume"

![SC_V_0_4_1 Follow and Assume_2525c_1](https://user-images.githubusercontent.com/49548300/66773413-34973600-eebf-11e9-84d9-a7d65a8c98c4.jpg)

**Comment by dehmer** [comment]
Thus this very issue to support them.
I should have provided an issue description. 
My bad.

**Comment by dehmer** [comment]
fixed.
