### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by csingewald** [syncpoint/ODIN#130]
Print/Eport snapshots of the map  (printer, PDF, image)

**Comment by ThomasHalwax** [comment]
For printing I think PDF is the way to go. Maybe we can limit ourselves to discrete scales like 1:50000 and 1:10000.

**Comment by ThomasHalwax** [comment]
After doing some research there seem to be two strategies to create maps with correct scale on paper:
* Stitch existing tiles together and scale the resulting image to the width/length required.
* Use a renderer like Mapnik oder MapboxGL Native to render raw data to PDF. Obviously this is only possible for vector based (non legacy) maps.
