### ISSUE TITLE
Tactical graphics "Main attack" and "Supporting attack" not displayed correctly

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#140]
The tactical graphics "Main attack" (SIDC: G*GPOLKGM-****X) and "Supporting attack" (SIDC: G*GPOLKGS-****X ) are not displayed correctly on the map (only as a line).

If the object is marked with the mouse, the "location points" are displayed offset on the map.

![SC_V_0_4_1 Main and Supporting Attack](https://user-images.githubusercontent.com/49548300/66774354-b2f4d780-eec1-11e9-80b4-eb637fdd6963.jpg)

The correct representation according to MIL-STD-2525-C:

"Main attack":

![SC_V_0_4_1 Direction of Attack 2525c](https://user-images.githubusercontent.com/49548300/66774242-6f01d280-eec1-11e9-853c-30b286f4b3e9.jpg)

"Supporting attack":

![SC_V_0_4_1 Direction of Attack Support  2525c](https://user-images.githubusercontent.com/49548300/66774389-c011c680-eec1-11e9-86d4-756aebe10d1e.jpg)

**Comment by dehmer** [comment]
Both are not supported, yet.
