### ISSUE TITLE
Tactical graphic "Counterattack" not displayed correctly on the map

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#141]
When the tactical graphic "Counterattack" is displayed on the map and the user zooms the map in or out, the "geographical" location of the attack arrow changes depending on the zoom level.

For the "Counterattack", the display must be correctly positioned regardless of the zoom level.

For example:

Scale 1 : 8000:

![SC_V_0_4_1 Counterattack Zomm 1_8000](https://user-images.githubusercontent.com/49548300/66774944-264b1900-eec3-11e9-8260-78428b6b06b2.jpg)

Scale 1 : 70.000:

![SC_V_0_4_1 Counterattack Zomm 1_70000](https://user-images.githubusercontent.com/49548300/66774965-37942580-eec3-11e9-928c-0d5594c6728c.jpg)

Scale 1 : 150.000:

![SC_V_0_4_1 Counterattack Zoom 1_150000](https://user-images.githubusercontent.com/49548300/66774977-3fec6080-eec3-11e9-88cd-cf538b477068.jpg)

If you zoom too far into or out of the map, the tactical graphic "Counterattack" disappears from the map at all.

And if the user crosses the locations, the end point of the arrow is displayed infinitely long on the map:

![SC_V_0_4_1 Counterattack incorrect display](https://user-images.githubusercontent.com/49548300/66775450-48916680-eec4-11e9-9eb3-96b592788f10.jpg)

**Comment by dehmer** [comment]
Location should not change with zooming. This is a possible subsequent error; maybe an invalid geometry. Please check DevTools in these cases for error messages.

I filed an issue to make CATK editing (and similar) more robust (your last picture).
See #142.

<img width="1011" alt="Screen Shot 2019-10-14 at 22 01 33" src="https://user-images.githubusercontent.com/322462/66779567-ceb2aa80-eece-11e9-9080-2819469b1b9a.png">
<img width="1011" alt="Screen Shot 2019-10-14 at 22 01 48" src="https://user-images.githubusercontent.com/322462/66779590-d5412200-eece-11e9-8093-36e1f3d72cad.png">
