### ISSUE TITLE
Unit "Target Acquisition Sound" is displayed incorrectly as a line

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#143]
The unit "Target Acquisition Sound" is not displayed correctly as a unit, but as a line on the map.

The settings are displayed by an unit, but on the map the display and behavior of the object is like a general line.

![SC_V_0_4_1 Unit Sound Artillery wrong](https://user-images.githubusercontent.com/49548300/66860321-3fb89780-ef8d-11e9-8e45-74d6501fdb45.jpg)

**Comment by dehmer** [comment]
fixed.
