### ISSUE TITLE
Symbol Palette: Feature set for recently used features

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODIN#146]
Create a 'virtual' feature set (named 'Recently used'), which contains the last six distinct features drawn on the map. Persisting the entries is optional but desired. The entries should be managed in LRU-style: https://en.wikipedia.org/wiki/Cache_replacement_policies#Most_recently_used_(MRU)

**Comment by JulianKK** [comment]
done in feature/recentlyUsed without persistence

**Comment by dehmer** [comment]
merged.
