### ISSUE TITLE
Lines are not beautifully displayed in the Version Preview 0.5.0

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#154]
In the version Preview 0.5.0 the edges of the lines and rooms are no longer displayed "beautifully" (solid):

![SC Lines not beautiful 1](https://user-images.githubusercontent.com/49548300/68384709-7e8ad900-0158-11ea-97bd-65fe6b49382c.jpg)

![SC Lines not beautiful 2](https://user-images.githubusercontent.com/49548300/68384714-82b6f680-0158-11ea-9fa6-73cdfeffeb09.jpg)

**Comment by dehmer** [comment]
Wow, I had no idea that high-performance rendering options would have this terrible impact on other platforms. Reverting to original settings (auto) for next release.

Current settings:
* text-rendering: auto (default) | __optimizeSpeed__ | optimizeLegibility | geometricPrecision
* shape-rendering: auto (default) | __optimizeSpeed__ | crispEdges | geometricPrecision

<img width="688" alt="Screen Shot 2019-11-08 at 08 00 16" src="https://user-images.githubusercontent.com/322462/68456902-4d191880-01ff-11ea-9cf7-5b04becae68e.png">

* text-rendering: auto (default) | optimizeSpeed | __optimizeLegibility__ | geometricPrecision
* shape-rendering: auto (default) | optimizeSpeed | crispEdges | __geometricPrecision__
<img width="688" alt="Screen Shot 2019-11-08 at 07 59 47" src="https://user-images.githubusercontent.com/322462/68456773-00354200-01ff-11ea-8bd9-c6f287517d60.png">

New settings:
* text-rendering: __auto__ (default) | optimizeSpeed | optimizeLegibility | geometricPrecision
* shape-rendering: __auto__ (default) | optimizeSpeed | crispEdges | geometricPrecision
<img width="644" alt="Screen Shot 2019-11-08 at 08 07 16" src="https://user-images.githubusercontent.com/322462/68457038-98332b80-01ff-11ea-86d6-64a6396739d2.png">
