### ISSUE TITLE
Installation symbols are rendered without the 'installation indicator'

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/ODIN#160]
Installations like 'Police Installation' are rendered without the appropriate indicator. Exporting the layer shows that the indicator 'H' is missing in the SIDC.

This seems to be an odd issue because all symbols are rendered correctly (in the palette as well as on the map) if the are contained in a feature set. The lack the installation indicator if they are found by the keyword search.

Using 'Equipment manufacture' as an example: it is the first entry in the 'Installations' feature set and is rendered correctly.
<img width="307" alt="image" src="https://user-images.githubusercontent.com/38359572/72452216-78028880-37bd-11ea-8d8e-dfb31ab9b07c.png">
If you search for 'Equipment manufacture' the feature is found but is rendered without the installation indicator.
<img width="315" alt="image" src="https://user-images.githubusercontent.com/38359572/72452319-a54f3680-37bd-11ea-9e00-f33f923a1c1d.png">

**Comment by ThomasHalwax** [comment]
The feature-descriptors.json file contains an incomplete SIDC for installations. When changing the SIDC from 'S*G*IE----*****' to 'S*G*IE----H****' the symbol is rendered correctly.

**Comment by ThomasHalwax** [comment]
@dehmer Is the file 'feature-descriptors.json' generated or is it hand-crafted?

**Comment by dehmer** [comment]
`feature-descriptors.json` contains symbols and graphics derived from MIP/MIG database.
The database view contained wrong SIDC formatting code.
