### ISSUE TITLE
Missing properties for Ground Installations

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/ODIN#166]
No property editor for SIDCs

- SFGPIXH---H-: [EMS.OPN.EMMED.HSP] EMERGENCY MEDICAL OPERATION / HOSPITAL
- SFGPIRP---H-: [EMS.INFSTR.ENGFAC.PETFAC] PETROLEUM FACILITY

common part of the SIDC seems to be ```S*G*I```

**Comment by dehmer** [comment]
Also
* EFOPDJC---H****: [EFOPDJC---H****] - POLICE INSTALLATION

More more general E*O*------H**** for EMS Operations Installations

**Comment by dehmer** [comment]
For now added the following properties for installations.
Re-open if something is missing.

<img width="728" alt="Screenshot 2020-02-14 at 12 07 37" src="https://user-images.githubusercontent.com/322462/74526401-a215aa80-4f23-11ea-899e-4ed35550e1a8.png">
