### ISSUE TITLE
Missing properties for Emergency Management Infrastructure

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/ODIN#167]
examples for SIDCs are

- ENFPF------- (governmental site infrastructure)
- EFFPCD------ (COMMERCIAL INFRASTRUCTURE - HAZARDOUS MATERIAL PRODUCTION)
- EFFPMA------ (WATER SUPPLY INFRASTRUCTURE - CONTROL VALVE)

common part of the SIDC seems to be ```E*F```

**Comment by dehmer** [comment]
E*F* in 2525C are Emergency Management Symbol (EMS) Infrastructure symbols (mostly installations).

**Comment by ThomasHalwax** [comment]
Some symbols from the hierarchy "EMERGENCY MANAGEMENT SYMBOLS INFRASTRUCTURE" do not have the indicator ```H``` for installations. 

```E*FPMA----*****``` (WATER SUPPLY INFRASTRUCTURE CONTROL VALVE)
```E*FPMC----*****``` (WATER SUPPLY INFRASTRUCTURE DISCHARGE OUTFALL)
```E*FPBA----*****``` (BANKING FINANCE AND INSURANCE INFRASTRUCTURE ATM)

The 2525C documents shows them as equipments. Since they are part of the infrastructure hierarchy I'd suggest to add the ```H``` indicator in order to use the same properties editor.

**Comment by ThomasHalwax** [comment]
In MilStd 2525D all symbols mentioned above are equipped with the indicator for installations:
![10032000001214030000](https://user-images.githubusercontent.com/38359572/74549407-dd2dd300-4f4f-11ea-9033-dac41f31a9d4.png)
![10032000001214010000](https://user-images.githubusercontent.com/38359572/74549460-f6368400-4f4f-11ea-9294-66c8f9d3123e.png)
![10032000001202010000](https://user-images.githubusercontent.com/38359572/74549559-22ea9b80-4f50-11ea-8364-75bb932a3fc2.png)
