### ISSUE TITLE
add installation indicator "H" to some "EMERGENCY MANAGEMENT SYMBOLS INFRASTRUCTURE" symbols

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/ODIN#169]
Some symbols from the hierarchy "EMERGENCY MANAGEMENT SYMBOLS INFRASTRUCTURE" do not have the indicator ```H``` for installations. 

```E*FPMA----*****``` (WATER SUPPLY INFRASTRUCTURE CONTROL VALVE)
```E*FPMC----*****``` (WATER SUPPLY INFRASTRUCTURE DISCHARGE OUTFALL)
```E*FPBA----*****``` (BANKING FINANCE AND INSURANCE INFRASTRUCTURE ATM)

The 2525C documents shows them as equipments. Since they are part of the infrastructure hierarchy I'd suggest to add the ```H``` indicator to the ```feature-descriptors.json``` in order to use the same properties editor.

_Originally posted by @ThomasHalwax in https://github.com/syncpoint/ODIN/issues/167#issuecomment-586361967_

**Comment by dehmer** [comment]
I'm reluctant to change the standard definitions, although milsymbol can probably handle this quite well.

There are some examples of 'same' symbols with and without installation indicator and different SIDCs (`EFOPA-----*****` vs. `EFOPAC----H****`). I'm not sure, if the installation indicator is 'optional' or an integral part of SIDCs, i.e. not a parameter like status. I lean towards the latter.

Inventing new identifiers may also lead to interoperability issues with downstream systems which are more strict.

**Comment by ThomasHalwax** [comment]
> 5.3.4.5 Installation indicator. The installation indicator is a shaded block used to show that a particular symbol denotes an installation. **Although installations are included in the symbol hierarchy, the addition of an installation indicator can turn any tactical symbol (except Signals Intelligence symbology—appendix D) into an installation**. The indicator is represented in field AC as defined in table IV and is positioned as shown in figures 2 and 3.

For Emergency Management Installations the installation indicator is part of the SIDC.
But ```E*F*MC----*****``` has an ```*``` on position 11. Doesn't that mean that the user/system can decide if this symbol has an installation indicator?

**Comment by dehmer** [comment]
I must say, that I'm pretty confused right now. But I see great potential in learning something here...

1. I didn't know that even equipment-like symbols might carry an installation indicator (see WATER CRAFT below). I'm not sure if this should be allowed. We should ask S/J 4 about this.
2. Symbols which initially come as an installation in 2525C may 'lose' their indicator (see WATER SUPPY SERVICES below)
3. Some symbols are contained in different hierarchies: `S*G*IUP---H****` is named WATER SUPPLY INFRASTRUCTURE in EMS hierarchy and PUBLIC WATER SERVICES in GROUND TRACK/INSTALLATIONS hierarchy. Go figure!
4. Some symbols have different function IDs depending whether it is an installation or not (EMERGENCY OPERATION/INSTALLATION)
5. Symbols looking the same, may have different function IDs (EMERGENCY OPERATION [UNIT])
6. milsymbol seems to even out problems in 2525C: EMERGENCY TEAM has a dedicated function ID, but in is only rendered 'correctly' when echelon A - team is specified: `EFO-BJ----*A***`
7. And even EMERGENCY TEAM/INSTALLATION is possible `EFO-BJ----HA***`

<img width="656" alt="Screenshot 2020-02-16 at 10 26 02" src="https://user-images.githubusercontent.com/322462/74602227-c948b500-50a6-11ea-830a-d0b7ed33db22.png">

To get back to the initial point: For a wide range of symbols we could allow adding/removing installation indicator by the user. We would add installation indicator by default for those mentioned by you above.

I'm still not sure how other systems can cope with this kind of flexibility. Next month I will check with our MIP friends in Greding.

**Comment by dehmer** [comment]
After some more thinking and talking I propose to leave 2525C unchanged and rather focus on supporting 2525D directly as our default symbology standard (still supporting 2525C).
This would iron out obvious flaws in 2525C and avoid possible issues or special case handling with data exchange. 2525D is also more in line with our national regulations anyway.

I already added a possible 2525 C/D mapping in the repository: https://github.com/syncpoint/ODIN/blob/develop/doc/sym_2525d.xlsx
I think this list was originally compiled by ESRI. So kudos to them for their effort.

Please feel free to open a new issue for MIL-STD 2525D support.
Also, if you are OK with this approach, please close this issue.

**Comment by ThomasHalwax** [comment]
> Please feel free to open a new issue for MIL-STD 2525D support.
> Also, if you are OK with this approach, please close this issue.

That's fine with me!
