### ISSUE TITLE
Stability Operations - Symbols are missing or wrong displayed on the map

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#172]
The display of the **"frame"** of the symbols of the subareas "Violent Activities", "Operations" and "Rape" is already **analogous to 2525d** and not according to 2525c.

Due to the intention of the changeover in ODIN to 2525d, **in my opinion no action is necessary**.

When switching to 2525d, the change in the "frame" of the symbols of the sub-areas "Individual", "Non-Military Group or Organization", "Items" and "Locations" must be taken into account (provided that they remain in the "Activities" area and have not been "moved" to other areas of 2525d).

**Comment by harrywipperfuerth** [comment]
### **_Update 23jun20:_**

Due to the change from version 0.5.4 to version 0.6.0/OL and the resulting reimplementation of the symbols 2525C, the following incorrect representations in the stability operations range were found during the check:

The display of the symbols on the map is basically correct for all, concerning the display of the **"frame"** according 2525d - **see first comment** from 25feb20!

For **the better use** of the stability operations symbols for the user, the **property set** should be **improved in the next time!**

At the moment, ODIN use the property set for units therefore, but these properties makes not really sense for this symbols.

Concerning the **_possible content_** and the structure of a "first" propertey set (= implementation of those modifiers that can already be used/displayed in ODIN) **_see Issue #194._**

**Comment by dehmer** [comment]
No further action required.
Closing.
