### ISSUE TITLE
METOC- Symbols are missing on the map

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#173]
The area "METOC" is currently not represented in ODIN and an implementation is not planned at present.

Nevertheless the area "METOC" should be added to the backlog as a reminder, because an at least partial implementation of single symbols seems to be possible in cooperation with other systems.

I know, it has no priority at the moment, but you should keep this in the "corner of your eye".

**Comment by dehmer** [comment]
There will be no METOC symbology in the foreseeable future.
No reminder either. Sorry, closing.
