### ISSUE TITLE
Emergency Management - Symbols are missing or wrong displayed on the map

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#174]
The following symbols for emergency management are missing or wrong displayed on the map:

SIDC 2525c (following example all with the Modifier (F) for friend on the Postion 2) / Hierachy Code:

EFOPDK----H**** / EMS.OPN.LAWENF.PRSN
**modifier field "AC" (Installation) is missing**

EFOPBJ----***** / EMS.OPN.EMOPN.EMTM
**modifier field "B" (Echelon) is missing**

OFOPHA----***** / EMS.INCDNT.AIR.HJKG
OFOPHV----***** / EMS.INCDNT.MRN.HJKG
OFOPHT----***** / EMS.INCDNT.VEH.HJKG
**is only displayed on the map with the "Activity Frame" for stability operation symbols, but not, as in 2525c, also for emergency management symbols with the standard frame**

EFIPGB----***** / EMS.INCDNT.RAIL.HJCK
**"H" should be more on the right side (not in the middle)**

EFIPG-----***** / EMS.INCDNT.RAIL
EFIPGA----***** / EMS.INCDNT.RAIL.ACDNT
**text modifier is from 2525d (ACC, INC), not from 2525c (A, I) and should be more on the right side (not in the middle)**

EFIPE-----***** / EMS.INCDNT.AIR
EFIPEA----***** / EMS.INCDNT.AIR.ACDNT
EFIPF-----***** / EMS.INCDNT.MRN
EFIPFA----***** / EMS.INCDNT.MRN.ACDNT
EFIPH-----***** / EMS.INCDNT.VEH
EFIPHA----***** / EMS.INCDNT.VEH.ACDNT
**text modifier is from 2525d (ACC, INC), not from 2525c (A, I)**

OFOPD-----***** / EMS.INCDNT.CVDIS.DEMO
OFIPR-----***** / EMS.INCDNT.CVDIS.DISPOP
OFVPB-----***** / EMS.INCDNT.CRMACT.BM
EFIPBF----***** / EMS.INCDNT.CRMACT.SHTG
EFIPDO----***** / EMS.INCDNT.HAZMAT.UNXORD
WAS-WSVE--P---- / EMS.NATEVT.GEO.VOLERN
WAS-WSD-LIP---- / EMS.NATEVT.HYDMET.DZ
E*NPBB----***** / EMS.NATEVT.HYDMET.DRGHT
WAS-WSGRL-P---- / EMS.NATEVT.HYDMET.HL
WAS-WSR-LIP---- / EMS.NATEVT.HYDMET.RA
WAS-WSDSLMP---- / EMS.NATEVT.HYDMET.DT/SD
WAS-WSS-LIP---- /  EMS.NATEVT.HYDMET.SN
WAS-WSTMH-P---- / EMS.NATEVT.HYDMET.TSTRM
WAS-WST-FCP---- / EMS.NATEVT.HYDMET.TNDO
WAS-WSTSS-P---- / EMS.NATEVT.HYDMET.TRPCYC
EFOPDOA---***** / EMS.OPN.SNS
EFOPDOA---***** / EMS.OPN.SNS.BIO
EFOPDOA---***** / EMS.OPN.SNS.CML
EFOPDOA---***** / EMS.OPN.SNS.INT
EFOPDOA---***** / EMS.OPN.SNS.NUC
EFOPDOA---***** / EMS.OPN.SNS.RAD
SFGPUULC--***** / EMS.OPN.LAWENF.POL.POLUNT
EFFPEA----H**** / EMS.INFSTR.ENGFAC.GENSTA
EFFPEB----H**** / EMS.INFSTR.ENGFAC.NTLGAS
EFFPEE----H**** / EMS.INFSTR.ENGFAC.PROPNE
EFFPLA----H**** / EMS.INFSTR.TSP.ATCF
EFFPLD----H**** / EMS.INFSTR.TSP.BSTN
EFFPLE----H**** / EMS.INFSTR.TSP.FRYTRM
EFFPLF----H**** / EMS.INFSTR.TSP.HLS
WOS-ML----P---- / EMS.INFSTR.TSP.LCK
EFFPLH----H**** / EMS.INFSTR.TSP.MAINTF
SFGPIBN---H**** / EMS.INFSTR.TSP.SP
EFFPLJ----H**** / EMS.INFSTR.TSP.RLSTN
EFFPLK----H**** / EMS.INFSTR.TSP.RSTSTP
WOS-HPBA--P---- / EMS.INFSTR.TSP.ANCRG
EFFPLM----H**** / EMS.INFSTR.TSP.TOLLF
EFFPLO----H**** / EMS.INFSTR.TSP.TIF
EFFPLP----H**** / EMS.INFSTR.TSP.TNL
EFFPMA----***** / EMS.INFSTR.WS.CV
EFFPMB----H**** / EMS.INFSTR.WS.DAM
EFFPMB----H**** / EMS.INFSTR.WS.DO
EFFPMC----***** / EMS.INFSTR.WS.GWWELL
EFFPMD----H**** / EMS.INFSTR.WS.PMPSTN
EFFPME----H**** / EMS.INFSTR.WS.RSVR
EFFPMG----H**** / EMS.INFSTR.WS.STRTWR
EFFPMH----H**** / EMS.INFSTR.WS.SWI
EFFPMI----H**** / EMS.INFSTR.WS.WH20TF
**no symbol could be created on the map**

**Comment by harrywipperfuerth** [comment]
### **_Update 23jun20_**

(the entry of 25feb20 must therefore be regarded as oboslet):

Due to the change from version 0.5.4 to version 0.6.0/OL and the resulting reimplementation of the symbols 2525C, the following incorrect representations in the EMS range were found during the check:

The following symbols for EMS are wrong displayed or missing on the map:

SIDC 2525c (following example all with the Modifier (F) for friend on the Position 2) / Hierachy Code:

EFOPDK----H**** / EMS.OPN.LAWENF.PRSN
**_modifier field "AC" (Installation) is missing_**

EFOPBJ----***** / EMS.OPN.EMOPN.EMTM
_**modifier field "B" (Echelon) is missing**_

OFOPHA----***** / EMS.INCDNT.AIR.HJKG
OFOPHV----***** / EMS.INCDNT.MRN.HJKG
OFOPHT----***** / EMS.INCDNT.VEH.HJKG
**_is only displayed on the map with the "Activity Frame" for stability operation symbols, but not, as in 2525c, also for emergency management symbols with the standard frame_**

EFIPGB----***** / EMS.INCDNT.RAIL.HJCK
**_"H" should be more on the right side (not in the middle)_**

EFIPG-----***** / EMS.INCDNT.RAIL
EFIPGA----***** / EMS.INCDNT.RAIL.ACDNT
**_text modifier is from 2525d (ACC, INC), not from 2525c (A, I) and should be more on the right side (not in the middle)_**

EFIPE-----***** / EMS.INCDNT.AIR
EFIPEA----***** / EMS.INCDNT.AIR.ACDNT
EFIPF-----***** / EMS.INCDNT.MRN
EFIPFA----***** / EMS.INCDNT.MRN.ACDNT
EFIPH-----***** / EMS.INCDNT.VEH
EFIPHA----***** / EMS.INCDNT.VEH.ACDNT
**_text modifier is from 2525d (ACC, INC), not from 2525c (A, I)_**

OFOPD-----***** / EMS.INCDNT.CVDIS.DEMO
OFIPR-----***** / EMS.INCDNT.CVDIS.DISPOP
OFVPB-----***** / EMS.INCDNT.CRMACT.BM
OFVPP-----***** / EMS.INCDNT.CRMACT.PSNG
**_the same symbol is in stability operations available, but yout don't find it as EMS symbol**

G*SPPO----****X / EMS.INFSTR.TSP.TCP
**_the same symbol is in tactical graphics - CSS Points available, but yout don't find it as EMS symbol**

SFSPNM----***** / EMS.OPN.EMMED.HSPSHP
**_the same symbol is in sea surface tracks available, but yout don't find it as EMS symbol**

EFIPDO----***** / EMS.INCDNT.HAZMAT.UNXORD
OFOPHA----***** / EMS.INCDNT.AIR.HJKG
OFOPHV----***** / EMS.INCDNT.MRN.HJKG
OFOPHT----***** / EMS.INCDNT.VEH.HJKG
WAS-WSVE--P---- / EMS.NATEVT.GEO.VOLERN
WAS-WSD-LIP---- / EMS.NATEVT.HYDMET.DZ
WAS-WSFGSOP---- / EMS.NATEVT.HYDMET.FG
WAS-WSGRL-P---- / EMS.NATEVT.HYDMET.HL
WAS-WSR-LIP---- / EMS.NATEVT.HYDMET.RA
WAS-WSDSLMP---- / EMS.NATEVT.HYDMET.DT/SD
WAS-WSS-LIP---- / EMS.NATEVT.HYDMET.SN
WAS-WSTMH-P---- / EMS.NATEVT.HYDMET.TSTRM
WAS-WST-FCP---- / EMS.NATEVT.HYDMET.TNDO
WAS-WSTSS-P---- / EMS.NATEVT.HYDMET.TRPCYC
EFOPCD----H**** / EMS.OPN.FIRFT.OTHH2O
EFOPCE----H**** / EMS.OPN.FIRFT.FIRSTN
EFOPBC----H**** / EMS.OPN.EMOPN.INS
EFOPBE----H**** / EMS.OPN.EMOPN.EICC
EFOPBF----H**** / EMS.OPN.EMOPN.EOC
EFOPBG----H**** / EMS.OPN.EMOPN.EPIC
EFOPBH----H**** / EMS.OPN.EMOPN.EMSHLT
EFOPBI----H**** / EMS.OPN.EMOPN.ESA
EFOPBK----H**** / EMS.OPN.EMOPN.EWDC
EFOPBL----H**** / EMS.OPN.EMOPN.FDDIST
EFOPAC----H**** / EMS.OPN.EMMED.INS
EFOPAD----H**** / EMS.OPN.EMMED.EMTLOC
EFOPAG----H**** / EMS.OPN.EMMED.HDF
SFGPIXH---H**** / EMS.OPN.EMMED.HSP
EFOPAJ----H**** / EMS.OPN.EMMED.MFOP
EFOPAK----H**** / EMS.OPN.EMMED.MRG
EFOPAL----H**** / EMS.OPN.EMMED.RX
EFOPAM----H**** / EMS.OPN.EMMED.TRIAGE
EFOPDC----H**** / EMS.OPN.LAWENF.LAWENI
EFOPDEC---H**** / EMS.OPN.LAWENF.BDRPT.BDRPTI
EFOPDFC---H**** /EMS.OPN.LAWENF.CSTM.CSTMIN
SFGPUULC--***** / EMS.OPN.LAWENF.POL.POLUNT
EFOPDJC---H**** / EMS.OPN.LAWENF.POL.POLINS
SFSPXL----***** / EMS.OPN.LAWENF.CSTGD.CSTGDE
EFOPDNC---H**** / EMS.OPN.LAWENF.CSTGD.CSTGDI
EFOPDDC---H**** / EMS.OPN.LAWENF.ATF.ATFINS
EFOPDGC---H**** / EMS.OPN.LAWENF.DEA.DEAINS
EFOPDHC--H**** / EMS.OPN.LAWENF.DOJ.DOJINS
EFOPDIC---H**** / EMS.OPN.LAWENF.FBI.FBIINS
EFOPDLC---H**** / EMS.OPN.LAWENF.SECSR.SECSRI
EFOPDMC---H**** /| EMS.OPN.LAWENF.TSA.TSAINS
EFOPDOA---***** / EMS.OPN.LAWENF.USMAR.USMARI
EFFPD-----H**** / EMS.INFSTR.EDFAC
EFFPDA----H**** / EMS.INFSTR.EDFAC.COLUNI
EFFPDB----H**** / EMS.INFSTR.EDFAC.SCHOOL
EFFPF-----H**** / EMS.INFSTR.GVTSTE
EFFPG-----H**** / EMS.INFSTR.MIL
EFFPGA----H**** / EMS.INFSTR.MIL.ARMORY
SFGPIB----H**** / EMS.INFSTR.MIL.MILBF
EFFPH-----H**** / EMS.INFSTR.PSTSRV
EFFPHA----H**** / EMS.INFSTR.PSTSRV.PDC
EFFPHB----H**** / EMS.INFSTR.PSTSRV.PO
EFFPJ-----H**** / EMS.INFSTR.SPCNDS
EFFPJA----H**** / EMS.INFSTR.SPCNDS.ADLTDC
EFFPJB----H**** / EMS.INFSTR.SPCNDS.CHLDDC
EFFPJC----H**** / EMS.INFSTR.SPCNDS.ELDERC
EFFPK-----H**** / EMS.INFSTR.TELCOM
SFGPIUT---H**** / EMS.INFSTR.TELCOM.TCF
EFFPKB----H**** / EMS.INFSTR.TELCOM.TCTWR
EFFPA-----H**** / EMS.INFSTR.AGFD
EFFPAA----H**** / EMS.INFSTR.AGFD.AGLAB
EFFPAB----H**** / EMS.INFSTR.AGFD.AFL
EFFPAC----H**** / EMS.INFSTR.AGFD.CFDC
EFFPAD----H**** / EMS.INFSTR.AGFD.FRMRNC
EFFPAE----H**** / EMS.INFSTR.AGFD.FPC
EFFPAF----H**** / EMS.INFSTR.AGFD.FDRTL
EFFPAG----H**** / EMS.INFSTR.AGFD.GRSTR
EFFPB-----H**** / EMS.INFSTR.BFI
EFFPBA----***** / EMS.INFSTR.BFI.ATM
EFFPBB----H**** / EMS.INFSTR.BFI.BANK
EFFPBC----H**** / EMS.INFSTR.BFI.BLSTR
EFFPBD----H**** / EMS.INFSTR.BFI.FRB
EFFPBE----H**** / EMS.INFSTR.BFI.FINEX
EFFPBF----H**** / EMS.INFSTR.BFI.FSO
EFFPC-----H**** / EMS.INFSTR.CMCL
EFFPCA----H**** / EMS.INFSTR.CMCL.CMLPLN
EFFPCB----H**** / EMS.INFSTR.CMCL.FIRMAN
EFFPCC----H**** / EMS.INFSTR.CMCL.FIRRET
EFFPCD----H**** / EMS.INFSTR.CMCL.HZMTPR
EFFPCE----H**** / EMS.INFSTR.CMCL.HZMTST
EFFPCF----H**** / EMS.INFSTR.CMCL.INDSTE
EFFPCG----H**** / EMS.INFSTR.CMCL.LNDFL
EFFPCH----H**** / EMS.INFSTR.CMCL.RXMFG
EFFPCI----H**** / EMS.INFSTR.CMCL.CHWS
EFFPCJ----H**** / EMS.INFSTR.CMCL.TXRLIN
SFGPIUE---H**** / EMS.INFSTR.ENGFAC
EFFPEA----H**** / EMS.INFSTR.ENGFAC.GENSTA
EFFPEB----H**** / EMS.INFSTR.ENGFAC.NTLGAS
SFGPIUEN--H**** / EMS.INFSTR.ENGFAC.NUCFAC
SFGPIRP---H**** / EMS.INFSTR.ENGFAC.PETFAC
EFFPEE----H**** / EMS.INFSTR.ENGFAC.PROPNE
EFFPI-----H**** / EMS.INFSTR.PUBVEN
EFFPIA----H**** / EMS.INFSTR.PUBVEN.ENCFAC
EFFPIB----H**** / EMS.INFSTR.PUBVEN.OPNFAC
EFFPIC----H**** / EMS.INFSTR.PUBVEN.RECARE
EFFPID----H**** / EMS.INFSTR.PUBVEN.RELIG
SFGPIT----H**** / EMS.INFSTR.TSP
EFFPLA----H**** / EMS.INFSTR.TSP.ATCF
SFGPIBA---H**** / EMS.INFSTR.TSP.AIRPT
G*MPBCB---****X / EMS.INFSTR.TSP.BRG
EFFPLD----H**** / EMS.INFSTR.TSP.BSTN
EFFPLE----H**** / EMS.INFSTR.TSP.FRYTRM
EFFPLF----H**** / EMS.INFSTR.TSP.HLS
WOS-ML----P---- / EMS.INFSTR.TSP.LCK
EFFPLH----H**** / EMS.INFSTR.TSP.MAINTF
SFGPIBN---H**** / EMS.INFSTR.TSP.SP
EFFPLJ----H**** / EMS.INFSTR.TSP.RLSTN
EFFPLK----H**** / EMS.INFSTR.TSP.RSTSTP
WOS-HPBA--P---- / EMS.INFSTR.TSP.ANCRG
EFFPLM----H**** / EMS.INFSTR.TSP.TOLLF
EFFPLO----H**** / EMS.INFSTR.TSP.TIF
EFFPLP----H**** / EMS.INFSTR.TSP.TNL
SFGPIUP---H**** / EMS.INFSTR.WS
EFFPMB----H**** / EMS.INFSTR.WS.DAM
EFFPMC----***** / EMS.INFSTR.WS.GWWELL
EFFPMD----H**** / EMS.INFSTR.WS.PMPSTN
EFFPME----H**** / EMS.INFSTR.WS.RSVR
EFFPMG----H**** / EMS.INFSTR.WS.STRTWR
EFFPMH----H**** / EMS.INFSTR.WS.SWI
EFFPMI----H**** / EMS.INFSTR.WS.WH20TF
**_no symbol could be created on the map_**

**Comment by dehmer** [comment]
For now we completely ignore METOC (SIDCs starting with 'W'), even if the symbols are additionally included in EMS hierarchy.

**Comment by dehmer** [comment]
We have a few different issues here:
* Currently a symbol can only be contained in one hierarchy. This might even lead to different frames: regular vs. activity. As long as a similar symbol can be found, this is good enough for me.
* D text modifiers in C is good enough. I cannot imagine that Beckman would be inclined to change that.
* Some symbols are slightly incorrect (mainly text positioning). As long as users can leaf with this, we are good.

<img width="313" alt="Screenshot 2020-11-16 at 09 31 34" src="https://user-images.githubusercontent.com/322462/99229715-a93d5200-27ee-11eb-9544-4ed491d432c7.png">

 1. EFOPDK----H****: clarification needed - symbol or properties issue
 2. EFFPBA----*****: clarification needed - symbol or properties issue
 3. EFOPBJ----*****: clarification needed - symbol or properties issue
 4. OFOPHA----*****: slightly wrong icon (upstream)
 5. OFOPHV----*****: slightly wrong icon (upstream)
 6. OFOPHT----*****: slightly wrong icon (upstream)
 7. EFIPGB----*****: slightly wrong icon (upstream)
 8. EFIPG-----*****: slightly wrong icon (upstream)
 9. EFIPGA----*****: slightly wrong icon (upstream)
10. EFIPE-----*****: 2525D text modifier is good enough
11. EFIPEA----*****: 2525D text modifier is good enough
12. EFIPF-----*****: 2525D text modifier is good enough
13. EFIPFA----*****: 2525D text modifier is good enough
14. EFIPH-----*****: 2525D text modifier is good enough
15. EFIPHA----*****: 2525D text modifier is good enough
16. OFOPD-----*****: same SIDC in different hierarchies
17. OFIPR-----*****: same SIDC in different hierarchies
18. OFVPB-----*****: same SIDC in different hierarchies
19. OFVPP-----*****: same SIDC in different hierarchies
20. G*SPPO----****X: same SIDC in different hierarchies
21. G*MPBCB---****X: same SIDC in different hierarchies
22. SFSPNM----*****: same SIDC in different hierarchies
23. SFSPXL----*****: same SIDC in different hierarchies
24. SFGPIXH---H****: same SIDC in different hierarchies
25. SFGPES----*****: same SIDC in different hierarchies
26. SFGPIUE---H****: same SIDC in different hierarchies
27. SFGPIUEN--H****: same SIDC in different hierarchies
28. SFGPIRP---H****: same SIDC in different hierarchies
29. SFGPIUT---H****: same SIDC in different hierarchies
30. SFGPIT----H****: same SIDC in different hierarchies
31. SFGPIBA---H****: same SIDC in different hierarchies
32. SFGPIBN---H****: same SIDC in different hierarchies
33. SFGPUULC--*****: same SIDC in different hierarchies
34. SFGPIUP---H****: same SIDC in different hierarchies

**Comment by dehmer** [comment]
No further actions required.
Closing.
