### ISSUE TITLE
Tactical Graphics - Symbols are wrong displayed on the map

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#175]
The following symbols for tactical graphics are missing or wrong displayed on the map:

SIDC 2525c (following example some objects have an **"#" instead of "*"** in **position 2**, its also mean "*" in the **SIDC**, is a **_workaround_**, because **_GitHub didn't displayed the "*"_** in all SIDC in the preview) / Hierachy Code:

G*FPACPR--****X / TACGRP.FSUPP.ARS.C2ARS.PAA.RTG
**"PAA" only once at symbol, in 2525c once per "length", modifier "AM" (width in m) missing (neccessary ?)**

G*TPR-----****X / TACGRP.TSK.RIP
**"RIP" is on the line of the symbol, not in the middle**

G*GPDLF---****X / TACGRP.C2GM.DEF.LNE.FEBA
**in 2525c the FEBA is only the two boundary points, the line is a type of phase line**

G*GPDAB---****X / TACGRP.C2GM.DEF.ARS.BTLPSN
G#GPDABP--****X / TACGRP.C2GM.DEF.ARS.BTLPSN.PBNO
**field "B" (Echelon) is missing**

G*GPOLAA--****X / TACGRP.C2GM.OFF.LNE.AXSADV.ABN
**field "A" (Symbol) is missing**

G*FPACAI--****X / TACGRP.FSUPP.ARS.C2ARS.ACA.IRR
**field "H2" (GRIDS) is missing**

G*TPD-----****X / TACGRP.TSK.DSTY
G#TPI-----****X / TACGRP.TSK.ITDT
G#TPN-----****X / TACGRP.TSK.NEUT
Hostility Status "Neutral" and "Unknown" not displayed on the map

G*TPUS----****X / TACGRP.TSK.SEC.SCN
G#TPUG----****X / TACGRP.TSK.SEC.GUD
G#TPUC----****X / TACGRP.TSK.SEC.COV
**there is no place between the two letters (S, G or C)**

G*GPGLF---****X / TACGRP.C2GM.GNL.LNE.FLOT
**the line of the FLOT has the wrong "frame", also keep in mind if it friend or hostile**

G*MPOU----****X / TACGRP.MOBSU.OBST.UXO
G#FPATB---****X / TACGRP.FSUPP.ARS.ARATGT.BMARA
G#GPOAP---****X / TACGRP.C2GM.OFF.ARS.PBX
G#GPSAA---****X / TACGRP.C2GM.SPL.ARA.AHD
**there is only a area without the correct modifiers displayed**

G*MPOGF---****X / TACGRP.MOBSU.OBST.GNL.OFA
G#MPOGR---****X / TACGRP.MOBSU.OBST.GNL.ORA
G#MPSP----****X / TACGRP.MOBSU.SU.STRGPT
G#GPAAH---****X / TACGRP.C2GM.AVN.ARS.HIDACZ
G#MPNR----****X / TACGRP.MOBSU.CBRN.RADA
G#MPNB----****X / TACGRP.MOBSU.CBRN.BIOCA
G#MPNC----****X / TACGRP.MOBSU.CBRN.CMLCA
G#FPACZI--****X / TACGRP.FSUPP.ARS.C2ARS.ZOR.IRR
G#GPSAE---****X / TACGRP.C2GM.SPL.ARA.ENCMT
**there is only a area without the correct modifiers displayed and also the "frame" of the area isn't correct**

G*MPOGB---****X / TACGRP.MOBSU.OBST.GNL.BLT
G#MPOEB---****X / TACGRP.MOBSU.OBST.OBSEFT.BLK
G#MPOHO---****X / TACGRP.MOBSU.OBST.AVN.OHWIRE
G#GPALC---****X / TACGRP.C2GM.AVN.LNE.ACDR
G#GPALM---****X / TACGRP.C2GM.AVN.LNE.MRR
G#GPALS---****X / TACGRP.C2GM.AVN.LNE.SAAFR
G#GPALU---****X / TACGRP.C2GM.AVN.LNE.UAR
G#GPALL---****X / TACGRP.C2GM.AVN.LNE.LLTR
G#FPLTF---****X / TACGRP.FSUPP.LNE.LNRTGT.FPF
G#FPLCF---****X / TACGRP.FSUPP.LNE.C2LNE.FSCL
G#FPLCC---****X / TACGRP.FSUPP.LNE.C2LNE.CFL
G#FPLCR---****X / TACGRP.FSUPP.LNE.C2LNE.RFL
G#SPLRM---****X / TACGRP.CSS.LNE.SLPRUT.MSRUT
G#SPLRA---****X / TACGRP.CSS.LNE.SLPRUT.ASRUT
G#SPLRO---****X / TACGRP.CSS.LNE.SLPRUT.1WTRFF
G#SPLRT---****X / TACGRP.CSS.LNE.SLPRUT.ATRFF
G#SPLRW---****X / TACGRP.CSS.LNE.SLPRUT.2WTRFF
G#TPA-----****X / TACGRP.TSK.FLWASS
G#TPAS----****X / TACGRP.TSK.FLWASS.FLWSUP
G#GPOAF---****X / TACGRP.C2GM.OFF.ARS.AFP
G#GPOLKGM-****X / TACGRP.C2GM.OFF.LNE.DIRATK.GRD.MANATK
G#GPOLKGS-****X / TACGRP.C2GM.OFF.LNE.DIRATK.GRD.SUPATK
G#GPOLI---****X / TACGRP.C2GM.OFF.LNE.INFNLE
G#GPSLH---****X / TACGRP.C2GM.SPL.LNE.HGL
G#GPGLC---****X / TACGRP.C2GM.GNL.LNE.LOC
**there is only a line without the correct modifiers displayed**

G*MPOT----****X / TACGRP.MOBSU.OBST.TRIPWR
**there is a line on the map instead of a point location**

G*GPGLB---****X / TACGRP.C2GM.GNL.LNE.BNDS
**only one echelon on the line is necessary (only by enemy for every step), also the units are not displayed on the left/right side of the echelon**

G*TPT-----****X / TACGRP.TSK.DRT
**the seize arrows must to be exchanged (left/right)**

G*GPSLB---****X / TACGRP.C2GM.SPL.LNE.BRGH
**the object has to be displayed as a line, not as an area**

G*GPGPAC--****X / TACGRP.C2GM.GNL.PNT.ACTL.SUWR
**the object is wrong, it's from the symbol "rotary wing antisubmarine"**

**Comment by harrywipperfuerth** [comment]
### **_Update 23jun20_**

(the entry of 25feb20 must therefore be regarded as oboslet):

Due to the change from version 0.5.4 to version 0.6.0/OL and the resulting reimplementation of the symbols 2525C, the following incorrect representations in the equipment range were found during the check:

SIDC 2525c (following example some objects have an **_"#" instead of "*"_** in **_position 2_**, its also mean "" in the SIDC, is a _**workaround**_, because **_GitHub didn't displayed the ""_** in all SIDC in the preview) / Hierachy Code:

The following symbols for equipment are wrong displayed on the map:

G*FPACPR--****X | TACGRP.FSUPP.ARS.C2ARS.PAA.RTG
**_displayed only as a "normal" area, without "PAA" at the lines,  modifier "AM" (width in m) is missing, the area is not a rectangular polygon, looks like mor than the irregular version_**

G*FPACAI--****X | TACGRP.FSUPP.ARS.C2ARS.ACA.IRR
**_field "H2" (GRIDS) is missing_**


G*MPOGL---****X | TACGRP.MOBSU.OBST.GNL.LNE
G#MPOS----****X | TACGRP.MOBSU.OBST.ABS
G#MPOMC---****X | TACGRP.MOBSU.OBST.MNE.MCLST
G#MPOADU--****X | TACGRP.MOBSU.OBST.ATO.ATD.ATDUC
G#MPOADC--****X | TACGRP.MOBSU.OBST.ATO.ATD.ATDC
G#MPOAR---****X | TACGRP.MOBSU.OBST.ATO.ATDATM
G#MPOAW---****X | TACGRP.MOBSU.OBST.ATO.ATW
G#MPOT----****X | TACGRP.MOBSU.OBST.TRIPWR
G#MPOWU---****X | TACGRP.MOBSU.OBST.WREOBS.USP
G#MPOWS---****X | TACGRP.MOBSU.OBST.WREOBS.SNGFNC
G#MPOWD---****X | TACGRP.MOBSU.OBST.WREOBS.DBLFNC
G#MPOWA---****X | TACGRP.MOBSU.OBST.WREOBS.DAFNC
G#MPOWL---****X | TACGRP.MOBSU.OBST.WREOBS.LWFNC
G#MPOWH---****X | TACGRP.MOBSU.OBST.WREOBS.HWFNC
G#MPOWCS--****X | TACGRP.MOBSU.OBST.WREOBS.CCTA.SNG
G#MPOWCD--****X | TACGRP.MOBSU.OBST.WREOBS.CCTA.DBLSTD
G#MPOWCT--****X | TACGRP.MOBSU.OBST.WREOBS.CCTA.TRISTD
G#MPSL----****X | TACGRP.MOBSU.SU.FTFDLN
G#MPSP----****X | TACGRP.MOBSU.SU.STRGPT
G#MPOHO---****X | TACGRP.MOBSU.OBST.AVN.OHWIRE
G#GPGLB---****X | TACGRP.C2GM.GNL.LNE.BNDS
G#GPGLF---****X | TACGRP.C2GM.GNL.LNE.FLOT
G#GPGLC---****X | TACGRP.C2GM.GNL.LNE.LOC
G#GPGLP---****X | TACGRP.C2GM.GNL.LNE.PHELNE
**_only a normal line is displayed on the map (without correct modifier, correct frame ...)_**


G*MPOGZ---****X | TACGRP.MOBSU.OBST.GNL.Z
G#MPOGF---****X | TACGRP.MOBSU.OBST.GNL.OFA
G#MPOGR---****X | TACGRP.MOBSU.OBST.GNL.ORA
G#MPOU----****X | TACGRP.MOBSU.OBST.UXO
G#MPOFD---****X | TACGRP.MOBSU.OBST.MNEFLD.DYN
G#MPNR----****X | TACGRP.MOBSU.CBRN.RADA
G#MPNB----****X | TACGRP.MOBSU.CBRN.BIOCA
G#MPNC----****X | TACGRP.MOBSU.CBRN.CMLCA
G#GPSAE---****X | TACGRP.C2GM.SPL.ARA.ENCMT
G#GPGAF---****X | TACGRP.C2GM.GNL.ARS.FTFDAR
G#GPGAY---****X | TACGRP.C2GM.GNL.ARS.LAARA
G#GPGAZ---****X | TACGRP.C2GM.GNL.ARS.AIRFZ
G#GPPC----****X | TACGRP.C2GM.DCPN.DMYMD
**_only a normal area is displayed on the map (without correct modifier, correct frame ...)_**

G*SPLCM---****X | TACGRP.CSS.LNE.CNY.MCNY
G#SPLCH---****X | TACGRP.CSS.LNE.CNY.HCNY
**_no Modifiers displayed on map, fields "A" and "H1" are missinig in property set, therefore no display at the symbol is possible_**

G*GPDAB---****X | TACGRP.C2GM.DEF.ARS.BTLPSN
G#GPDABP--****X | TACGRP.C2GM.DEF.ARS.BTLPSN.PBNO
**_Modifier "B" for echelon is missing_**

G*MPOEF---****X | TACGRP.MOBSU.OBST.OBSEFT.FIX
G#MPBCF---****X | TACGRP.MOBSU.OBSTBP.CSGSTE.FRY
**_the arrowhead isn't filled in black_**

G*TPAS----****X | TACGRP.TSK.FLWASS.FLWSUP
_**the arrowhead isn't filled in black, Unique Destignation "T1" is too much, Hostility Status not all right (assumed friend, Suspected …)**_

G*SPLRO---****X | TACGRP.CSS.LNE.SLPRUT.1WTRFF
G#SPLRT---****X | TACGRP.CSS.LNE.SLPRUT.ATRFF
G#SPLRW---****X | TACGRP.CSS.LNE.SLPRUT.2WTRFF
**_the arrows in the symbol is missing, instead of that the full text is displayed_**

G*MPNL----****X | TACGRP.MOBSU.CBRN.DRCL
**_Modifier "T" isn't displayed on the map_**

G*FPLCC---****X | TACGRP.FSUPP.LNE.C2LNE.CFL
**_Modifier "T1" isn't displayed on the map_**

G*GPPM----****X | TACGRP.C2GM.DCPN.DMA
**_symbol for dummy inside the area isn't displayed on the map_**


G*GPPY----****X | TACGRP.C2GM.DCPN.DMAF
**_symbol for dummy inside the area and "X" isn't displayed on the map_**

**Comment by harrywipperfuerth** [comment]
**_Update 2 23jun20_**

The following symbols are displayed correct on the map.
The main problem here is that only rudimentary entries (Name, Unique Designation, Add Info) can currently be made in the displayed content of the property set and further modifiers/amplifiers cannot yet be entered here.

However, these are required for the display on the map (e.g. times etc.):


SIDC | Hierachy code
-- | --
G*GPGPAP--****X | TACGRP.C2GM.GNL.PNT.ACTL.CAP
G*GPGPAW--****X | TACGRP.C2GM.GNL.PNT.ACTL.ABNEW
G*GPGPAK--****X | TACGRP.C2GM.GNL.PNT.ACTL.TAK
G*GPGPAA--****X | TACGRP.C2GM.GNL.PNT.ACTL.ASBWF
G*GPGPAH--****X | TACGRP.C2GM.GNL.PNT.ACTL.ASBWR
G*GPGPAB--****X | TACGRP.C2GM.GNL.PNT.ACTL.SUWF
G*GPGPAC--****X | TACGRP.C2GM.GNL.PNT.ACTL.SUWR
G*GPGPAD--****X | TACGRP.C2GM.GNL.PNT.ACTL.MIWF
G*GPGPAE--****X | TACGRP.C2GM.GNL.PNT.ACTL.MIWR
G*GPGPAS--****X | TACGRP.C2GM.GNL.PNT.ACTL.SKEIP
G*GPGPAT--****X | TACGRP.C2GM.GNL.PNT.ACTL.TCN
G*GPGPAO--****X | TACGRP.C2GM.GNL.PNT.ACTL.TMC
G*GPGPAR--****X | TACGRP.C2GM.GNL.PNT.ACTL.RSC
G*GPGPAL--****X | TACGRP.C2GM.GNL.PNT.ACTL.RPH
G*GPGPAF--****X | TACGRP.C2GM.GNL.PNT.ACTL.UA
G*GPGPAG--****X | TACGRP.C2GM.GNL.PNT.ACTL.VTUA
G*GPGPAI--****X | TACGRP.C2GM.GNL.PNT.ACTL.ORB
G*GPGPAJ--****X | TACGRP.C2GM.GNL.PNT.ACTL.ORBF8
G*GPGPAM--****X | TACGRP.C2GM.GNL.PNT.ACTL.ORBRT
G*GPGPAN--****X | TACGRP.C2GM.GNL.PNT.ACTL.ORBRD
G*GPAPP---****X | TACGRP.C2GM.AVN.PNT.ACP
G*GPAPC---****X | TACGRP.C2GM.AVN.PNT.COMMCP
G*GPAPU---****X | TACGRP.C2GM.AVN.PNT.PUP
G*GPAPD---****X | TACGRP.C2GM.AVN.PNT.DAPP
G*GPGPC---****X | TACGRP.C2GM.GNL.PNT.SCTL
G*GPGPCU--****X | TACGRP.C2GM.GNL.PNT.SCTL.USV
G*GPGPCUR-****X | TACGRP.C2GM.GNL.PNT.SCTL.USV.RMV
G*GPGPCUA-****X | TACGRP.C2GM.GNL.PNT.SCTL.USV.ASW
G*GPGPCUS-****X | TACGRP.C2GM.GNL.PNT.SCTL.USV.SUW
G*GPGPCUM-****X | TACGRP.C2GM.GNL.PNT.SCTL.USV.MIW
G*GPGPCA--****X | TACGRP.C2GM.GNL.PNT.SCTL.ASW
G*GPGPCS--****X | TACGRP.C2GM.GNL.PNT.SCTL.SUW
G*GPGPCM--****X | TACGRP.C2GM.GNL.PNT.SCTL.MIW
G*GPGPCP--****X | TACGRP.C2GM.GNL.PNT.SCTL.PKT
G*GPGPCR--****X | TACGRP.C2GM.GNL.PNT.SCTL.RDV
G*GPGPCC--****X | TACGRP.C2GM.GNL.PNT.SCTL.RSC
G*GPGPCE--****X | TACGRP.C2GM.GNL.PNT.SCTL.REP
G*GPGPCN--****X | TACGRP.C2GM.GNL.PNT.SCTL.NCBTT
G*GPGPB---****X | TACGRP.C2GM.GNL.PNT.UCTL
G*GPGPBU--****X | TACGRP.C2GM.GNL.PNT.UCTL.UUV
G*GPGPBUA-****X | TACGRP.C2GM.GNL.PNT.UCTL.UUV.ASW
G*GPGPBUS-****X | TACGRP.C2GM.GNL.PNT.UCTL.UUV.SUW
G*GPGPBUM-****X | TACGRP.C2GM.GNL.PNT.UCTL.UUV.MIW
G*GPGPBS--****X | TACGRP.C2GM.GNL.PNT.UCTL.SBSTN
G*GPGPBSA-****X | TACGRP.C2GM.GNL.PNT.UCTL.SBSTN.ASW
G*GPGPUUD-****X | TACGRP.C2GM.GNL.PNT.USW.UH2.DTM
G*GPGPUUB-****X | TACGRP.C2GM.GNL.PNT.USW.UH2.BCON
G*GPGPUUL-****X | TACGRP.C2GM.GNL.PNT.USW.UH2.LCON
G*GPGPUUS-****X | TACGRP.C2GM.GNL.PNT.USW.UH2.SNK
G*GPGPUS--****X | TACGRP.C2GM.GNL.PNT.USW.SRH
G*GPGPUSA-****X | TACGRP.C2GM.GNL.PNT.USW.SRH.ARA
G*GPGPUSD-****X | TACGRP.C2GM.GNL.PNT.USW.SRH.DIPPSN
G*GPGPUSC-****X | TACGRP.C2GM.GNL.PNT.USW.SRH.CTR
G*GPGPUY--****X | TACGRP.C2GM.GNL.PNT.USW.SNBY
G*GPGPUYP-****X | TACGRP.C2GM.GNL.PNT.USW.SNBY.PTNCTR
G*GPGPUYD-****X | TACGRP.C2GM.GNL.PNT.USW.SNBY.DIFAR
G*GPGPUYL-****X | TACGRP.C2GM.GNL.PNT.USW.SNBY.LOFAR
G*GPGPUYC-****X | TACGRP.C2GM.GNL.PNT.USW.SNBY.CASS
G*GPGPUYS-****X | TACGRP.C2GM.GNL.PNT.USW.SNBY.DICASS
G*GPGPUYB-****X | TACGRP.C2GM.GNL.PNT.USW.SNBY.BT
G*GPGPUYA-****X | TACGRP.C2GM.GNL.PNT.USW.SNBY.ANM
G*GPGPUYV-****X | TACGRP.C2GM.GNL.PNT.USW.SNBY.VLAD
G*GPGPUYT-****X | TACGRP.C2GM.GNL.PNT.USW.SNBY.ATAC
G*GPGPUYR-****X | TACGRP.C2GM.GNL.PNT.USW.SNBY.RO
G*GPGPUYK-****X | TACGRP.C2GM.GNL.PNT.USW.SNBY.KGP
G*GPGPUYX-****X | TACGRP.C2GM.GNL.PNT.USW.SNBY.EXP
G*FPPTS---****X | TACGRP.FSUPP.PNT.TGT.PTGT
G*FPPCS---****X | TACGRP.FSUPP.PNT.C2PNT.SCP
G*FPPCB---****X | TACGRP.FSUPP.PNT.C2PNT.FP
G*FPPCR---****X | TACGRP.FSUPP.PNT.C2PNT.RP
G*FPPCH---****X | TACGRP.FSUPP.PNT.C2PNT.HP
G*FPPCL---****X | TACGRP.FSUPP.PNT.C2PNT.LP
G*SPPX----****X | TACGRP.CSS.PNT.AEP
G*SPPC----****X | TACGRP.CSS.PNT.CBNP
G*SPPY----****X | TACGRP.CSS.PNT.CCP
G*SPPT----****X | TACGRP.CSS.PNT.CVP
G*SPPD----****X | TACGRP.CSS.PNT.DCP
G*SPPE----****X | TACGRP.CSS.PNT.EPWCP
G*SPPL----****X | TACGRP.CSS.PNT.LRP
G*SPPM----****X | TACGRP.CSS.PNT.MCP
G*SPPR----****X | TACGRP.CSS.PNT.RRRP
G*SPPU----****X | TACGRP.CSS.PNT.ROM
G*SPPO----****X | TACGRP.CSS.PNT.TCP
G*SPPI----****X | TACGRP.CSS.PNT.TTP
G*SPPN----****X | TACGRP.CSS.PNT.UMC
G*SPPAS---****X | TACGRP.CSS.PNT.AP
G*SPPAT---****X | TACGRP.CSS.PNT.AP.ATP
G*SPPSZ---****X | TACGRP.CSS.PNT.SPT
G*SPPSA---****X | TACGRP.CSS.PNT.SPT.CLS1
G*SPPSB---****X | TACGRP.CSS.PNT.SPT.CLS2
G*SPPSC---****X | TACGRP.CSS.PNT.SPT.CLS3
G*SPPSD---****X | TACGRP.CSS.PNT.SPT.CLS4
G*SPPSE---****X | TACGRP.CSS.PNT.SPT.CLS5
G*SPPSF---****X | TACGRP.CSS.PNT.SPT.CLS6
G*SPPSG---****X | TACGRP.CSS.PNT.SPT.CLS7
G*SPPSH---****X | TACGRP.CSS.PNT.SPT.CLS8
G*SPPSI---****X | TACGRP.CSS.PNT.SPT.CLS9
G*SPPSJ---****X | TACGRP.CSS.PNT.SPT.CLS10
G*TPA-----****X | TACGRP.TSK.FLWASS
G*GPOPP---****X | TACGRP.C2GM.OFF.PNT.PNTD
G*GPDPT---****X | TACGRP.C2GM.DEF.PNT.TGTREF
G*GPDPO---****X | TACGRP.C2GM.DEF.PNT.OBSPST
G*GPDPOC--****X | TACGRP.C2GM.DEF.PNT.OBSPST.CBTPST
G*GPDPOR--****X | TACGRP.C2GM.DEF.PNT.OBSPST.RECON
G*GPDPOF--****X | TACGRP.C2GM.DEF.PNT.OBSPST.FWDOP
G*GPDPOS--****X | TACGRP.C2GM.DEF.PNT.OBSPST.SOP
G*GPDPON--****X | TACGRP.C2GM.DEF.PNT.OBSPST.CBRNOP
G*GPGPP---****X | TACGRP.C2GM.GNL.PNT.ACTPNT
G*GPGPPK--****X | TACGRP.C2GM.GNL.PNT.ACTPNT.CHKPNT
G*GPGPPC--****X | TACGRP.C2GM.GNL.PNT.ACTPNT.CONPNT
G*GPGPPO--****X | TACGRP.C2GM.GNL.PNT.ACTPNT.CRDPNT
G*GPGPPD--****X | TACGRP.C2GM.GNL.PNT.ACTPNT.DCNPNT
G*GPGPPL--****X | TACGRP.C2GM.GNL.PNT.ACTPNT.LNKUPT
G*GPGPPP--****X | TACGRP.C2GM.GNL.PNT.ACTPNT.PSSPNT
G*GPGPPR--****X | TACGRP.C2GM.GNL.PNT.ACTPNT.RAYPNT
G*GPGPPE--****X | TACGRP.C2GM.GNL.PNT.ACTPNT.RELPNT
G*GPGPPS--****X | TACGRP.C2GM.GNL.PNT.ACTPNT.STRPNT
G*GPGPPA--****X | TACGRP.C2GM.GNL.PNT.ACTPNT.AMNPNT
G*GPGPPW--****X | TACGRP.C2GM.GNL.PNT.ACTPNT.WAP
G*GPGPF---****X | TACGRP.C2GM.GNL.PNT.FRMN
G*GPGPH---****X | TACGRP.C2GM.GNL.PNT.HBR
G*GPGPHQ--****X | TACGRP.C2GM.GNL.PNT.HBR.PNTQ
G*GPGPHA--****X | TACGRP.C2GM.GNL.PNT.HBR.PNTA
G*GPGPHY--****X | TACGRP.C2GM.GNL.PNT.HBR.PNTY
G*GPGPHX--****X | TACGRP.C2GM.GNL.PNT.HBR.PNTX
G*GPGPO---****X | TACGRP.C2GM.GNL.PNT.RTE
G*GPGPOZ--****X | TACGRP.C2GM.GNL.PNT.RTE.RDV
G*GPGPOD--****X | TACGRP.C2GM.GNL.PNT.RTE.DVSN
G*GPGPOW--****X | TACGRP.C2GM.GNL.PNT.RTE.WAP
G*GPGPOP--****X | TACGRP.C2GM.GNL.PNT.RTE.PIM
G*GPGPOR--****X | TACGRP.C2GM.GNL.PNT.RTE.PNTR
G*GPGPRN--****X | TACGRP.C2GM.GNL.PNT.REFPNT.NAVREF
G*GPGPRS--****X | TACGRP.C2GM.GNL.PNT.REFPNT.SPLPNT
G*GPGPRD--****X | TACGRP.C2GM.GNL.PNT.REFPNT.DLRP
G*GPGPRP--****X | TACGRP.C2GM.GNL.PNT.REFPNT.PIM
G*GPGPRM--****X | TACGRP.C2GM.GNL.PNT.REFPNT.MRSH
G*GPGPRW--****X | TACGRP.C2GM.GNL.PNT.REFPNT.WAP
G*GPGPRC--****X | TACGRP.C2GM.GNL.PNT.REFPNT.CRDRTB
G*GPGPRI--****X | TACGRP.C2GM.GNL.PNT.REFPNT.PNTINR
G*GPGPWA--****X | TACGRP.C2GM.GNL.PNT.WPN.AIMPNT
G*GPGPWD--****X | TACGRP.C2GM.GNL.PNT.WPN.DRPPNT
G*GPGPWE--****X | TACGRP.C2GM.GNL.PNT.WPN.ENTPNT
G*GPGPWG--****X | TACGRP.C2GM.GNL.PNT.WPN.GRDZRO
G*GPGPWM--****X | TACGRP.C2GM.GNL.PNT.WPN.MSLPNT
G*GPGPWI--****X | TACGRP.C2GM.GNL.PNT.WPN.IMTPNT
G*GPGPWP--****X | TACGRP.C2GM.GNL.PNT.WPN.PIPNT

**Comment by dehmer** [comment]
In the future, smaller issues will be used to track implementation of missing or correcting exiting features.
In addition, with #364 it will be obvious to the user which features are currently not supported.
