### ISSUE TITLE
Tactical Graphics - Symbols are not displayed on the map

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#176]
The following symbols for tactical graphics aren't displayed on the map:

SIDC | Hierachy code | Status
-- | -- | --
G*MPOGL---****X | TACGRP.MOBSU.OBST.GNL.BLT | TODO
G*MPOGL---****X | TACGRP.MOBSU.OBST.GNL.LNE | TODO
G*MPOGZ---****X | TACGRP.MOBSU.OBST.GNL.Z | TODO
G*MPOGZ---****X | TACGRP.MOBSU.OBST.GNL.OFA | TODO
G*MPOGZ---****X | TACGRP.MOBSU.OBST.GNL.ORA | TODO
G*MPOS----****X | TACGRP.MOBSU.OBST.ABS | TODO
G*MPOET---****X | TACGRP.MOBSU.OBST.OBSEFT.TUR | TODO
G*MPOED---****X | TACGRP.MOBSU.OBST.OBSEFT.DRT | TODO
G*MPBDE---****X | TACGRP.MOBSU.OBSTBP.DFTY.ESY | TODO
G*MPBDD---****X | TACGRP.MOBSU.OBSTBP.DFTY.DFT | TODO
G*MPBDI---****X | TACGRP.MOBSU.OBSTBP.DFTY.IMP | TODO
G*MPBCA---****X | TACGRP.MOBSU.OBSTBP.CSGSTE.ASTCA | TODO
G*MPBCE---****X | TACGRP.MOBSU.OBSTBP.CSGSTE.FRDESY | TODO
G*MPBCD---****X | TACGRP.MOBSU.OBSTBP.CSGSTE.FRDDFT | TODO
G*MPOMC---****X | TACGRP.MOBSU.OBST.MNE.MCLST | TODO
G*MPOFD---****X | TACGRP.MOBSU.OBST.MNEFLD.DYN | TODO
G*MPOFG---****X | TACGRP.MOBSU.OBST.MNEFLD.GAP | TODO
G*MPOADU--****X | TACGRP.MOBSU.OBST.ATO.ATD.ATDUC | TODO
G*MPOADC--****X | TACGRP.MOBSU.OBST.ATO.ATD.ATDC | TODO
G*MPOAR---****X | TACGRP.MOBSU.OBST.ATO.ATDATM | TODO
G*MPOAW---****X | TACGRP.MOBSU.OBST.ATO.ATW | TODO
G*MPOWU---****X | TACGRP.MOBSU.OBST.WREOBS.USP | TODO
G*MPOWS---****X | TACGRP.MOBSU.OBST.WREOBS.SNGFNC | TODO
G*MPOWD---****X | TACGRP.MOBSU.OBST.WREOBS.DBLFNC | TODO
G*MPOWA---****X | TACGRP.MOBSU.OBST.WREOBS.DAFNC | TODO
G*MPOWL---****X | TACGRP.MOBSU.OBST.WREOBS.LWFNC | TODO
G*MPOWH---****X | TACGRP.MOBSU.OBST.WREOBS.HWFNC | TODO
G*MPOWCS--****X | TACGRP.MOBSU.OBST.WREOBS.CCTA.SNG | TODO
G*MPOWCD--****X | TACGRP.MOBSU.OBST.WREOBS.CCTA.DBLSTD | TODO
G*MPOWCT--****X | TACGRP.MOBSU.OBST.WREOBS.CCTA.TRISTD | TODO
G*MPORP---****X | TACGRP.MOBSU.OBST.RCBB.PLND | TODO
G*MPORS---****X | TACGRP.MOBSU.OBST.RCBB.SAFE | TODO
G*MPORA---****X | TACGRP.MOBSU.OBST.RCBB.ABP | TODO
G*MPORC---****X | TACGRP.MOBSU.OBST.RCBB.EXCD | TODO
G*MPSL----****X | TACGRP.MOBSU.SU.FTFDLN | TODO
G*MPNM----****X | TACGRP.MOBSU.CBRN.MSDZ | TODO
G*MPNL----****X | TACGRP.MOBSU.CBRN.DRCL | TODO
G*FPAXC---****X | TACGRP.FSUPP.ARS.WPNRF.CIRCLR | TODO
G*FPAXS---****X | TACGRP.FSUPP.ARS.WPNRF.SCR | TODO
G*SPLCM---****X | TACGRP.CSS.LNE.CNY.MCNY | TODO: labels
G*SPLCH---****X | TACGRP.CSS.LNE.CNY.HCNY | TODO: labels
G*TPZ-----****X | TACGRP.TSK.SZE | TODO
G*GPOAS---****X | TACGRP.C2GM.OFF.ARS.SFP | TODO
G*GPOLAV--****X | TACGRP.C2GM.OFF.LNE.AXSADV.AVN | TODO
G*GPOLAR--****X | TACGRP.C2GM.OFF.LNE.AXSADV.ATK | TODO
G*GPDLP---****X | TACGRP.C2GM.DEF.LNE.PDF | TODO
G*GPSLA---****X | TACGRP.C2GM.SPL.LNE.AMB | TODO
G*GPGAF---****X | TACGRP.C2GM.GNL.ARS.FTFDAR | TODO
G*GPGAS---****X | TACGRP.C2GM.GNL.ARS.SRHARA | TODO
G*GPGAZ---****X | TACGRP.C2GM.GNL.ARS.AIRFZ | TODO
G*GPPD----****X | TACGRP.C2GM.DCPN.DMY | TODO
G*GPPA----****X | TACGRP.C2GM.DCPN.AAFF | TODO
G*GPPM----****X | TACGRP.C2GM.DCPN.DMA | TODO
G*GPPY----****X | TACGRP.C2GM.DCPN.DMAF | TODO
G*GPPC----****X | TACGRP.C2GM.DCPN.DMYMD | TODO
G*GPOLKA--****X | TACGRP.C2GM.OFF.LNE.DIRATK.AVN | **DONE**
G*GPDAE---****X | TACGRP.C2GM.DEF.ARS.EMTARA | **DONE**
G*GPPF----****X | TACGRP.C2GM.DCPN.DAFF | **DONE**
G*MPOEF---****X | TACGRP.MOBSU.OBST.OBSEFT.FIX | **DONE**
G*MPBCF---****X | TACGRP.MOBSU.OBSTBP.CSGSTE.FRY | **DONE**
G*MPBCL---****X | TACGRP.MOBSU.OBSTBP.CSGSTE.LANE | **DONE**
G*MPBCR---****X | TACGRP.MOBSU.OBSTBP.CSGSTE.RFT | **DONE**
G*MPOFA---****X | TACGRP.MOBSU.OBST.MNEFLD.MNDARA | **DONE**
G*MPSW----****X | TACGRP.MOBSU.SU.FEWS | **DONE**
G*OPHN----****X | TACGRP.OTH.HAZ.NVGL | **DONE**
G*OPB-----****X | TACGRP.OTH.BERLNE | **DONE**
G*OPBE----****X | TACGRP.OTH.BERLNE.ELC | **DONE**
G*OPBA----****X | TACGRP.OTH.BERLNE.ACU | **DONE**
G*OPBT----****X | TACGRP.OTH.BERLNE.TPD | **DONE**
G*OPBO----****X | TACGRP.OTH.BERLNE.EOPI | **DONE**
G*FPLT----****X | TACGRP.FSUPP.LNE.LNRTGT | **DONE**
G*FPLTS---****X | TACGRP.FSUPP.LNE.LNRTGT.LSTGT | **DONE**
G*FPLCM---****X | TACGRP.FSUPP.LNE.C2LNE.MFP | **DONE**
G*FPACSI--****X | TACGRP.FSUPP.ARS.C2ARS.FSA.IRR | **DONE**
G*FPACEI--****X | TACGRP.FSUPP.ARS.C2ARS.SNSZ.IRR | **DONE**
G*FPACDI--****X | TACGRP.FSUPP.ARS.C2ARS.DA.IRR | **DONE**
G*FPACBI--****X | TACGRP.FSUPP.ARS.C2ARS.TBA.IRR | **DONE**
G*FPACVI--****X | TACGRP.FSUPP.ARS.C2ARS.TVAR.IRR | **DONE**
G*FPACT---****X | TACGRP.FSUPP.ARS.C2ARS.TGMF | **DONE**
G*F-AKBI--****X | TACGRP.FSUPP.ARS.KLBOX.BLUE.IRR | **DONE**
G*F-AKPI--****X | TACGRP.FSUPP.ARS.KLBOX.PURPLE.IRR | **DONE**
G*FPAZII--****X | TACGRP.FSUPP.ARS.TGTAQZ.ATIZ.IRR | **DONE**
G*FPAZXI--****X | TACGRP.FSUPP.ARS.TGTAQZ.CFFZ.IRR | **DONE**
G*FPAZCI--****X | TACGRP.FSUPP.ARS.TGTAQZ.CNS.IRR | **DONE**
G*FPAZFI--****X | TACGRP.FSUPP.ARS.TGTAQZ.CFZ.IRR | **DONE**
G*FPAT----****X | TACGRP.FSUPP.ARS.ARATGT | **DONE**
G*FPATG---****X | TACGRP.FSUPP.ARS.ARATGT.SGTGT | **DONE**
G*FPATS---****X | TACGRP.FSUPP.ARS.ARATGT.SMK | **DONE**
G*FPACSC--****X | ~~TACGRP.FSUPP.ARS.C2ARS.FSA.CIRCLR~~ | NOT SUPPORTED
G*FPACAC--****X | ~~TACGRP.FSUPP.ARS.C2ARS.ACA.CIRCLR~~ | NOT SUPPORTED
G*FPACFC--****X | ~~TACGRP.FSUPP.ARS.C2ARS.FFA.CIRCLR~~ | NOT SUPPORTED
G*FPACNC--****X | ~~TACGRP.FSUPP.ARS.C2ARS.NFA.CIRCLR~~ | NOT SUPPORTED
G*FPACRC--****X | ~~TACGRP.FSUPP.ARS.C2ARS.RFA.CIRCLR~~ | NOT SUPPORTED
G*FPACPC--****X | ~~TACGRP.FSUPP.ARS.C2ARS.PAA.CIRCLR~~ | NOT SUPPORTED
G*FPACEC--****X | ~~TACGRP.FSUPP.ARS.C2ARS.SNSZ.CIRCLR~~ | NOT SUPPORTED
G*FPACDC--****X | ~~TACGRP.FSUPP.ARS.C2ARS.DA.CIRCLR~~ | NOT SUPPORTED
G*FPACZC--****X | ~~TACGRP.FSUPP.ARS.C2ARS.ZOR.CIRCLR~~ | NOT SUPPORTED
G*FPACBC--****X | ~~TACGRP.FSUPP.ARS.C2ARS.TBA.CIRCLR~~ | NOT SUPPORTED
G*FPACVC--****X | ~~TACGRP.FSUPP.ARS.C2ARS.TVAR.CIRCLR~~ | NOT SUPPORTED
G*FPACSR--****X | ~~TACGRP.FSUPP.ARS.C2ARS.FSA.RTG~~ | NOT SUPPORTED
G*FPACAR--****X | ~~TACGRP.FSUPP.ARS.C2ARS.ACA.RTG~~ | NOT SUPPORTED
G*FPACFR--****X | ~~TACGRP.FSUPP.ARS.C2ARS.FFA.RTG~~ | NOT SUPPORTED
G*FPACNR--****X | ~~TACGRP.FSUPP.ARS.C2ARS.NFA.RTG~~ | NOT SUPPORTED
G*FPACRR--****X | ~~TACGRP.FSUPP.ARS.C2ARS.RFA.RTG~~ | NOT SUPPORTED
G*FPACER--****X | ~~TACGRP.FSUPP.ARS.C2ARS.SNSZ.RTG~~ | NOT SUPPORTED
G*FPACDR--****X | ~~TACGRP.FSUPP.ARS.C2ARS.DA.RTG~~ | NOT SUPPORTED
G*FPACZR--****X | ~~TACGRP.FSUPP.ARS.C2ARS.ZOR.RTG~~ | NOT SUPPORTED
G*FPACBR--****X | ~~TACGRP.FSUPP.ARS.C2ARS.TBA.RTG~~ | NOT SUPPORTED
G*FPACVR--****X | ~~TACGRP.FSUPP.ARS.C2ARS.TVAR.RTG~~ | NOT SUPPORTED
G*F-AKBC--****X | ~~TACGRP.FSUPP.ARS.KLBOX.BLUE.CIRCLR~~ | NOT SUPPORTED
G*F-AKBR--****X | ~~TACGRP.FSUPP.ARS.KLBOX.BLUE.RTG~~ | NOT SUPPORTED
G*F-AKPC--****X | ~~TACGRP.FSUPP.ARS.KLBOX.PURPLE.CIRCLR~~ | NOT SUPPORTED
G*F-AKPR--****X | ~~TACGRP.FSUPP.ARS.KLBOX.PURPLE.RTG~~ | NOT SUPPORTED
G*FPAZIR--****X | ~~TACGRP.FSUPP.ARS.TGTAQZ.ATIZ.RTG~~ | NOT SUPPORTED
G*FPAZXR--****X | ~~TACGRP.FSUPP.ARS.TGTAQZ.CFFZ.RTG~~ | NOT SUPPORTED
G*FPAZCR--****X | ~~TACGRP.FSUPP.ARS.TGTAQZ.CNS.RTG~~ | NOT SUPPORTED
G*FPAZFR--****X | ~~TACGRP.FSUPP.ARS.TGTAQZ.CFZ.RTG~~ | NOT SUPPORTED
G*FPATR---****X | ~~TACGRP.FSUPP.ARS.ARATGT.RTGTGT~~ | NOT SUPPORTED
G*FPATC---****X | ~~TACGRP.FSUPP.ARS.ARATGT.CIRTGT~~ | NOT SUPPORTED

**Comment by harrywipperfuerth** [comment]
### **_Update 23jun20_**

(the entry of 25feb20 must therefore be regarded as oboslet):

Due to the change from version 0.5.4 to version 0.6.0/OL and the resulting reimplementation of the symbols 2525C, the following incorrect representations in the equipment range were found during the check:

The following symbols for equipment are not displayed on the map yet:


SIDC | Hierachy code
-- | --
G*MPOGB---****X | TACGRP.MOBSU.OBST.GNL.BLT
G*MPOEB---****X | TACGRP.MOBSU.OBST.OBSEFT.BLK
G*MPOET---****X | TACGRP.MOBSU.OBST.OBSEFT.TUR
G*MPOED---****X | TACGRP.MOBSU.OBST.OBSEFT.DRT
G*MPBDE---****X | TACGRP.MOBSU.OBSTBP.DFTY.ESY
G*MPBDD---****X | TACGRP.MOBSU.OBSTBP.DFTY.DFT
G*MPBDI---****X | TACGRP.MOBSU.OBSTBP.DFTY.IMP
G*MPBCA---****X | TACGRP.MOBSU.OBSTBP.CSGSTE.ASTCA
G*MPBCB---****X | TACGRP.MOBSU.OBSTBP.CSGSTE.BRG
G*MPBCE---****X | TACGRP.MOBSU.OBSTBP.CSGSTE.FRDESY
G*MPBCD---****X | TACGRP.MOBSU.OBSTBP.CSGSTE.FRDDFT
G*MPOFG---****X | TACGRP.MOBSU.OBST.MNEFLD.GAP
G*MPORP---****X | TACGRP.MOBSU.OBST.RCBB.PLND
G*MPORS---****X | TACGRP.MOBSU.OBST.RCBB.SAFE
G*MPORA---****X | TACGRP.MOBSU.OBST.RCBB.ABP
G*MPORC---****X | TACGRP.MOBSU.OBST.RCBB.EXCD
G*GPGPA---****X | TACGRP.C2GM.GNL.PNT.ACTL
G*GPALC---****X | TACGRP.C2GM.AVN.LNE.ACDR
G*GPALM---****X | TACGRP.C2GM.AVN.LNE.MRR
G*GPALS---****X | TACGRP.C2GM.AVN.LNE.SAAFR
G*GPALU---****X | TACGRP.C2GM.AVN.LNE.UAR
G*GPALL---****X | TACGRP.C2GM.AVN.LNE.LLTR
G*OPB-----****X | TACGRP.OTH.BERLNE
G*MPNM----****X | TACGRP.MOBSU.CBRN.MSDZ
G*FPAXC---****X | TACGRP.FSUPP.ARS.WPNRF.CIRCLR
G*FPAXS---****X | TACGRP.FSUPP.ARS.WPNRF.SCR
G*FPACSC--****X | TACGRP.FSUPP.ARS.C2ARS.FSA.CIRCLR
G*FPACAC--****X | TACGRP.FSUPP.ARS.C2ARS.ACA.CIRCLR
G*FPACFC--****X | TACGRP.FSUPP.ARS.C2ARS.FFA.CIRCLR
G*FPACNC--****X | TACGRP.FSUPP.ARS.C2ARS.NFA.CIRCLR
G*FPACRC--****X | TACGRP.FSUPP.ARS.C2ARS.RFA.CIRCLR
G*FPACPC--****X | TACGRP.FSUPP.ARS.C2ARS.PAA.CIRCLR
G*FPACEC--****X | TACGRP.FSUPP.ARS.C2ARS.SNSZ.CIRCLR
G*FPACDC--****X | TACGRP.FSUPP.ARS.C2ARS.DA.CIRCLR
G*FPACZC--****X | TACGRP.FSUPP.ARS.C2ARS.ZOR.CIRCLR
G*FPACBC--****X | TACGRP.FSUPP.ARS.C2ARS.TBA.CIRCLR
G*FPACVC--****X | TACGRP.FSUPP.ARS.C2ARS.TVAR.CIRCLR
G*FPACSR--****X | TACGRP.FSUPP.ARS.C2ARS.FSA.RTG
G*FPACAR--****X | TACGRP.FSUPP.ARS.C2ARS.ACA.RTG
G*FPACFR--****X | TACGRP.FSUPP.ARS.C2ARS.FFA.RTG
G*FPACNR--****X | TACGRP.FSUPP.ARS.C2ARS.NFA.RTG
G*FPACRR--****X | TACGRP.FSUPP.ARS.C2ARS.RFA.RTG
G*FPACER--****X | TACGRP.FSUPP.ARS.C2ARS.SNSZ.RTG
G*FPACDR--****X | TACGRP.FSUPP.ARS.C2ARS.DA.RTG
G*FPACZR--****X | TACGRP.FSUPP.ARS.C2ARS.ZOR.RTG
G*FPACBR--****X | TACGRP.FSUPP.ARS.C2ARS.TBA.RTG
G*FPACVR--****X | TACGRP.FSUPP.ARS.C2ARS.TVAR.RTG
G*F-AKBC--****X | TACGRP.FSUPP.ARS.KLBOX.BLUE.CIRCLR
G*F-AKBR--****X | TACGRP.FSUPP.ARS.KLBOX.BLUE.RTG
G*F-AKPC--****X | TACGRP.FSUPP.ARS.KLBOX.PURPLE.CIRCLR
G*F-AKPR--****X | TACGRP.FSUPP.ARS.KLBOX.PURPLE.RTG
G*FPAZIR--****X | TACGRP.FSUPP.ARS.TGTAQZ.ATIZ.RTG
G*FPAZXR--****X | TACGRP.FSUPP.ARS.TGTAQZ.CFFZ.RTG
G*FPAZCR--****X | TACGRP.FSUPP.ARS.TGTAQZ.CNS.RTG
G*FPAZFR--****X | TACGRP.FSUPP.ARS.TGTAQZ.CFZ.RTG
G*FPATR---****X | TACGRP.FSUPP.ARS.ARATGT.RTGTGT
G*FPATC---****X | TACGRP.FSUPP.ARS.ARATGT.CIRTGT
G*TPH-----****X | TACGRP.TSK.BRH
G*TPY-----****X | TACGRP.TSK.BYS
G*TPK-----****X | TACGRP.TSK.CATK
G*TPKF----****X | TACGRP.TSK.CATK.CATKF
G*TPO-----****X | TACGRP.TSK.OCC
G*TPR-----****X | TACGRP.TSK.RIP
G*TPM-----****X | TACGRP.TSK.RTM
G*TPS-----****X | TACGRP.TSK.SCE
G*TPUS----****X | TACGRP.TSK.SEC.SCN
G*TPUG----****X | TACGRP.TSK.SEC.GUD
G*TPUC----****X | TACGRP.TSK.SEC.COV
G*TPZ-----****X | TACGRP.TSK.SZE
G*TPW-----****X | TACGRP.TSK.WDR
G*TPWP----****X | TACGRP.TSK.WDR.WDRUP
G*TPB-----****X | TACGRP.TSK.BLK
G*TPC-----****X | TACGRP.TSK.CNZ
G*TPX-----****X | TACGRP.TSK.CLR
G*TPJ-----****X | TACGRP.TSK.CNT
G*TPL-----****X | TACGRP.TSK.DLY
G*TPT-----****X | TACGRP.TSK.DRT
G*TPE-----****X | TACGRP.TSK.ISL
G*TPP-----****X | TACGRP.TSK.PNE
G*TPQ-----****X | TACGRP.TSK.RTN
G*GPOAF---****X | TACGRP.C2GM.OFF.ARS.AFP
G*GPOAS---****X | TACGRP.C2GM.OFF.ARS.SFP
G*GPOLAV--****X | TACGRP.C2GM.OFF.LNE.AXSADV.AVN
G*GPOLAA--****X | TACGRP.C2GM.OFF.LNE.AXSADV.ABN
G*GPOLAR--****X | TACGRP.C2GM.OFF.LNE.AXSADV.ATK
G*GPOLAGM-****X | TACGRP.C2GM.OFF.LNE.AXSADV.GRD.MANATK
G*GPOLAGS-****X | TACGRP.C2GM.OFF.LNE.AXSADV.GRD.SUPATK
G*GPOLI---****X | TACGRP.C2GM.OFF.LNE.INFNLE
G*GPDLP---****X | TACGRP.C2GM.DEF.LNE.PDF
G*GPSLA---****X | TACGRP.C2GM.SPL.LNE.AMB
G*GPSLB---****X | TACGRP.C2GM.SPL.LNE.BRGH
G*GPGPR---****X | TACGRP.C2GM.GNL.PNT.REFPNT
G*GPGAS---****X | TACGRP.C2GM.GNL.ARS.SRHARA
G*GPPD----****X | TACGRP.C2GM.DCPN.DMY
G*GPPA----****X | TACGRP.C2GM.DCPN.AAFF

**Comment by dehmer** [comment]
In the future, smaller issues will be used to track implementation of missing features.
In addition, with #364 it will be obvious to the user which features are currently not supported.
