### ISSUE TITLE
Define a set of Tactical Graphics for MVP

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/ODIN#208]
We need a set of TG and their SIDC, descriptions, etc. in order to provide the minimal functionality required by S2 and S3 roles.

**Comment by harrywipperfuerth** [comment]
In the appendix my proposal of the content for the set "Tactical Graphics for MVP".

[Set TG for MVP_16mar20.xlsx](https://github.com/syncpoint/ODIN/files/4337408/Set.TG.for.MVP_16mar20.xlsx)

**Comment by dehmer** [comment]
Is this issue still valid, or do we rather implement 2525C completely?
Or maybe this set could this be used to prioritize?
Please comment.

**Comment by harrywipperfuerth** [comment]
**_In my opinion, our priority should be to fully implement the MIL-STD 2525C._**

The Excel list I sent in my earlier comment would not be the same today.

My suggestion would be that the user can show/hide the Armed Forces sections **Land**, Air (**Space** and **Air**), Maritme (**Surface** and **Subsurface**) and **SOF** by activating them in the map palette and thus limit the hit display.

As a combination I would suggest that this should also be possible for the sub-areas of MIL-STD 2525C (**Unit, Equipment, Installation, Tactical Graphics, SIGINT, Stability Operations, EMS**).

![grafik](https://user-images.githubusercontent.com/49548300/99230968-40ef7000-27f0-11eb-8c9c-6c9d887776d4.png)

**Tags** could be used to assign the individual symbols to the respective areas.

**Comment by dehmer** [comment]
@harrywipperfuerth Your suggestion is a usability issue we can consider, but - as far as I can see - has nothing to do with this issue.
The question here is if we want to prioritize S2/S3 symbology.
My answer would be no, we implement 2525C as good as possible. S2/S3 stuff would be included automatically.

**Comment by harrywipperfuerth** [comment]
I understand, then I would suggest to include the usability topic as a separate issue, because I already see a need for action for usability here.

In the course of this, one could also evaluate whether to provide own "sets" for the different roles (not only for S2/S3, but also for the other areas like S4, S6 etc.) by means of tags.

**Comment by dehmer** [comment]
Yes please. Do it.
Smells like two different 'improvements' to me.
