### ISSUE TITLE
Location search: Order results by Euclidean distance from map center

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODIN#23]
It is reasonable to assume, that the (military) user usually want's to find places in near proximity to current map view port.

**Comment by harrywipperfuerth** [comment]
In most cases this will be the most probable case, which can be assumed, however the location search (far) outside of the current map picture cannot be excluded.

The search should therefore start in the middle of the current map viewpoint.

If the user knows that he has to search for a location far away from the current map viewpoint, he should be able to enter a new starting point for the search. For example, if he wants to search for a place in another country, he can enter the name of the country or a city nearby as a new starting point, and thus get a different order of possible hits for his search.

**Comment by dehmer** [comment]
Done.

**Comment by dehmer** [comment]
@harrywipperfuerth OSM Nominatim, the search engine we are currently using, supports this kind of search. 'Zeltweg Österreich' or 'Zeltweg Austria' finds 'our' Zeltweg, even when the map is centered on Zeltweg Switzerland (or Germany.)
