### ISSUE TITLE
Geometry Editor: Support multi-select for multiple features

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODIN#231]

**Comment by dehmer** [comment]
OL 'select' interaction supports option multi: boolean, which when enabled allows to select multiple/all features under the mouse pointer with __one__ click (see screenshot below). This option is consciously disabled because it is probably not what the user expects. SHIFT-click is still possible to select multiple features, though.

<img width="362" alt="Screenshot 2020-03-25 at 08 44 22" src="https://user-images.githubusercontent.com/322462/77513383-2dfce980-6e75-11ea-87f6-c9fbc8a2eced.png">

**Comment by dehmer** [comment]
Also to be considered as multi-select:
* Select All
* Box Selection (Lasso)

**Comment by ThomasHalwax** [comment]
@dehmer Can we close this issue? I think it's resolved with #277 .

**Comment by dehmer** [comment]
Fixed. Closing.
