### ISSUE TITLE
Map/pan: Feature redraw broken when mouse is released outside window

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODIN#238]
When mouse pointer is released outside the window while panning the map, feature parts which come into view are not drawn. In the following example, map is vertically panned from top to bottom. The second screenshot shows the part which is not updated. Clicking inside the window again will finally update the missing portions (third screenshot).

Initial picture:
<img width="625" alt="Screenshot 2020-03-25 at 09 10 41" src="https://user-images.githubusercontent.com/322462/77516314-766ad600-6e7a-11ea-962d-e19e86ee2f88.png">

Missing updates after panning down:
<img width="625" alt="Screenshot 2020-03-25 at 09 10 54" src="https://user-images.githubusercontent.com/322462/77516357-8d112d00-6e7a-11ea-9705-014fcdc00c17.png">

Back to normal after click into window:
<img width="625" alt="Screenshot 2020-03-25 at 09 23 26" src="https://user-images.githubusercontent.com/322462/77516394-a0bc9380-6e7a-11ea-8440-75a69f5439a2.png">

**Comment by ThomasHalwax** [comment]
Open Layers has been updated to [v6.3.0](https://github.com/openlayers/openlayers/releases/tag/v6.3.0). Using this version I am no longer able to reproduce this issue (at lease on MacOS X).
Can someone else please confirm?

**Comment by weinma** [comment]
Can't reproduce it either.

**Comment by ThomasHalwax** [comment]
@dehmer Can you please also confirm that this issue is resolved by the update of OL and can be closed?

**Comment by dehmer** [comment]
I cannot find any related fix the 6.3.0 release notes, but can no longer reproduce either.
Closing.
