### ISSUE TITLE
"Unable to create basic Accelerated OpenGL renderer" on MacOS

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/ODIN#243]
OSX Catalina 10.15.4, Electron 8.11

When editing symbols on the map the refresh rate seems to be limited to a value between 16 and 20 fps. The electron console gives a hint:

```shell
Unable to create basic Accelerated OpenGL renderer.
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.
```

Since Apple deprecates OpenGL in favor of Metal there seems to be an issue with the OpenGL support in chromium. See the related issue for [electron](https://github.com/electron/electron/issues/20944)

**Comment by dehmer** [comment]
These messages seem to be related to DevTools/Performance only. For me they don't appear as long as DevTools are closed.
Currently I see no reason to follow up on this.

**Comment by dehmer** [comment]
@ThomasHalwax Please close when you think this can be ignored for now.

**Comment by dehmer** [comment]
Until now, no negative side-effects are noticed. Closing.
Re-open if necessary.

**Comment by PippoRaimondi** [comment]
`$ git gui` is unusable (very slow) because of this
