### ISSUE TITLE
support multiple tile providers (TP)

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/ODIN#267]
A user should be able to select different basemaps. To do so we need to provide a management ui where the tile providers can be added, edited and deleted (CRUD operations). The TP settings do not dependent on project settings, instead they are a template for individual projects.

Since there are many different standards about how to consume (rendered) tiles we will support:

1) XYZ TP like OSM
2) WMTS TP
3) Vector TP with additional styling (this is optional)

**Comment by dehmer** [comment]
@ThomasHalwax Apart from open issues, can this be closed?

**Comment by ThomasHalwax** [comment]
Will close this for now and create a new issue for each new feature request.
