### ISSUE TITLE
Display of property panels for multiple selection of objects

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#269]
If an object on the map is selected in ODIN, the property panel appears on the right-hand side, in which the user can enter or change the properties of the object on the map.

How does the program behave if several objects are selected with multi select?

Some Examples:
- No display of the property panel.
- Display of the property panel and only those properties that are the same for all are displayed.
- Display of each individual object and the user can "click through".

Furthermore, it would have to be judged whether all the same properties can be changed at once (e.g. marked objects on the map change from neutral to hostile).

We should assess and discuss this in detail.

**Comment by ThomasHalwax** [comment]
Well, I think for now (MVP) we should not show any properties when multiple objects are selected.

**Comment by dehmer** [comment]
Deferred. Closing.
