### ISSUE TITLE
Menu: Clipboard shortcuts not working (Windows)

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODIN#280]
Clipboard shortcuts CUT/COPY/PASTE in edit menu have no effect on Windows platform.
UNDO/REDO in same menu seem to work just right.

This might be an upstream Electron issue, since there are quite some reports for seemingly the same problem.

**Comment by dehmer** [comment]
For Linux the same problem exists.

**Comment by ThomasHalwax** [comment]
@csingewald or @harrywipperfuerth Can you please confirm that the key bindings are now working with Linux and Windows? Potentially fixed by #282

**Comment by csingewald** [comment]
The clipboard shortcuts are working with Linux and Windows.
