### ISSUE TITLE
update or replace deprecated dependency to phantom.js

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/ODIN#286]
By using ```icon-gen``` as a dev-dependency we have a deprecated binary inside of odin. Please check if this can be updated or removed:

```bash
npm install --save-dev icon-gen
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
```

**Comment by csingewald** [comment]
Removed icon-gen entry from package.json
