### ISSUE TITLE
Version 0.6.0/OL - Layer name hide Icons "lock" and "eye" in the activity bar

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#289]
In version 0.6.0/OL (current build from 07may20) too long layer names hide the icons for locking/unlocking the editing of a layer ("lock") or for showing/hiding the layer on map ("eye") in the activity bar. These icons are therefore difficult for the user to recognize.

Layer names that are too long should be displayed "cut off" here.

A limitation of the maximum length for layer names would also be a possibility. But I would not prefer this, because otherwise the users would be forced to use (too) short names often and other users would not be able to draw clear conclusions about the content of the layer because of the layer name. 

Maybe the complete layer name could be displayed additionally by a tooltip.

**Comment by ThomasHalwax** [comment]
Layer names are limited to a length of 64 characters and are not allowed to contain special characters (reserved characters for the filesystem). Longer names are wrapped:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/38359572/82750755-86d3fa00-9db2-11ea-9151-8abaa74b6ffa.png">
