### ISSUE TITLE
Version 0.6.0/OL - New created maps is displayed in a wrong way

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#290]
In version 0.6.0/OL (current build from 07may20) you can now use the menu bar to integrate other online maps into ODIN.

However, the newly created maps are not displayed correctly in the activity bar.

Instead of adding the newly created map, the newly created map appears instead of the OSM map (= base map). For the user it appears, that the OSM has been "overwritten".

After closing ODIN and restarting the program, all maps are displayed correctly in the activity bar.

For example:

First view (= initial situation):

![Odin Kartenerstellung 1](https://user-images.githubusercontent.com/49548300/81835092-1e7b5200-9542-11ea-805f-85f9d55b4a54.jpg)

Second view (= after creating a new map):

![Odin Kartenerstellung 2](https://user-images.githubusercontent.com/49548300/81835117-23d89c80-9542-11ea-98ba-0b03912cb024.jpg)

Third view (= after exit and restart of ODIN):

![Odin Kartenerstellung 3](https://user-images.githubusercontent.com/49548300/81835138-2a671400-9542-11ea-8ce1-ad1c1eb3b883.jpg)

**Comment by ThomasHalwax** [comment]
@harrywipperfuerth After #292 is merged we'll provide a new build. Please verify if the problem still exists.

**Comment by dehmer** [comment]
Is this fixed? If so, please close.

**Comment by harrywipperfuerth** [comment]
In the last time the error did not occur anymore. I think it is fixed and the issue can be closed.

If the bug occurs again, we have to open the issue.
