### ISSUE TITLE
i18n: missing key for en in namespace electron: exportProject.title

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODIN#311]

**Comment by ThomasHalwax** [comment]
Sorry, I can't reproduce this issue. The current entry in both the English and the German translation is
```json
"export": {
    "title": "Export {{name}}"
}
```

**Comment by ThomasHalwax** [comment]
Ahh, found the invalid reference ```exportProject.title``` in ```share-project```. This should become ```export.title```.
