### ISSUE TITLE
Change in the method of operation when creating installations in 0.6.0/OL

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#317]
In version 0.6.0./OL the creation of the installation icons has been changed.

Here it is now possible to set the _**installation indicator**_ (Modifier (2525C)/Amplifier (2525D) "AC") _**for all symbols**_ by pressing the button "I" (in the button bar at the top) in the map palette.

This **_makes no sense for about 95% of the symbols_** from a tactical point of view (e.g. a tac grapics - points, weapon systems, ships etc. are not installations)!

Furthermore, the assignment of the _**modifiers/amplifiers "AC"**_ according to 2525C or 2525D _**is not provided for most of the symbols**_ (e.g. Tac Grapics, METOC etc.).

![grafik](https://user-images.githubusercontent.com/49548300/85527450-2cc19100-b60b-11ea-9e2b-d353c1625fbf.png)

![grafik](https://user-images.githubusercontent.com/49548300/85527577-482c9c00-b60b-11ea-8d9a-fb2818fc0233.png)

![grafik](https://user-images.githubusercontent.com/49548300/85527985-ace7f680-b60b-11ea-868f-79e0a01e3ce5.png)

My suggestion in this respect is that the _**user can only create those symbols**_ as installations in the system **_which are intended for this_** according to 2525C or 2525D.

**Comment by ThomasHalwax** [comment]
This is fixed with #330 . No more button to switch to installations but a powerful search engine:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/38359572/92500383-5bf4a100-f1fd-11ea-894f-fec2939e9d94.png">
