### ISSUE TITLE
Include branded application 'About Dialog'

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODIN#33]
This is probably not what we want:

<img width="396" alt="Screen Shot 2019-05-21 at 10 32 24" src="https://user-images.githubusercontent.com/322462/58080594-cd957f80-7bb3-11e9-9bfc-e4f4402824ee.png">

We have to define, what information should be included in this dialog. Some suggestions:

* Syncpoint name, logo, company link (if possible)
* Application version
* Copyright notice
* 'Hecho en Viena con mucho ❤️' (just kiddin', or ...)

**Comment by dehmer** [comment]
For better error reporting, we can include some dependency versions: electron, chrome, node and v8.

**Comment by dehmer** [comment]
done.

**Comment by ThomasHalwax** [comment]
This needs to be done for 0.6.0/ol, too.
