### ISSUE TITLE
Redo/Undo - does not always work correctly

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#332]
**_1) White map_**

In the latest beta version 0.6.0 from 08.09.2020, when using the Redo/Undo functions, it can happen that the map in the ODIN becomes completely white and the user can only fix this by restarting.

This behavior occurs when the user cuts an object on the map, then inserts other objects and then executes the "Undo" function until the cut object is affected (either already there or shortly after).

**_2) Change location of an object_**

Another problem is, if the user creates objects and assigns a new location to one of them and adds more objects to the layer.

If the user then executes the "Undo" function, this works correctly in ODIN.

But if the user uses the "Redo" function again, this will only work exactly up to the copied object. The change of location and all other created objects are not restored.

**_3) Import Layer(s)_**

If the user imports a Layer via Drag & Drop (= this Layer becomes the active Layer automatically) and presses the "Undo" function immediately afterwards, the following steps (= each step is a click on Undo-Button) visible to the user are performed in ODIN:

   a) The layer on the map will be hidden.
   b) The imported layer is no longer the active layer and the layer selected before the import becomes the active layer again.
   c) The name of the imported layer is deleted, but a layer named "New Layer" is displayed.
   d) The "New Layer" is deleted.

Only after the fourth click on Undo is the original state restored.

For example, if the user imports three layers at the same time via drag & drop and wants to undo this immediately, the user has to press the Undo button 12 times in total to get back to the original state.

**Comment by ThomasHalwax** [comment]
I can only reproduce issue 1) if I create a new layer and then execute a few steps followed by a few + 1 (!) UNDO steps. Seems like we're trying to undo the creation of a new layer and that causes the error.
