### ISSUE TITLE
Map Palette - Missing Circular and Rectangular Fire Support Areas

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#346]
Currently it is not possible to display circular and rectangular fire support areas in ODIN on the map.

In order to be able to display the Fire Support Areas correctly in the corresponding plans, these two areas should also be displayed in ODIN.

Although the user can also map the rectangular representation using the already implemented variant of irregular geometry, this requires a higher processing effort, as the user must manually take the exact distance into account.

See also Issue #193 for the presentation including the properties.

**Comment by dehmer** [comment]
depends on #375

**Comment by ThomasHalwax** [comment]
Rectangular areas are implemented in #447
