### ISSUE TITLE
Map Palette - temporary cancellation of the selection of circular and rectangular FSA

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#348]
If the user searches for Fire Support Areas (FSA) in the Map Palette, all possible hits are displayed.

Currently the user can also select the cirular and rectangular FSA, but these are not displayed on the map.

Until the implementation (see also Issues #346 and #193), they should not be displayed in the selection.

**Comment by dehmer** [comment]
Is this limited to FSA? I imagine that there are other circular/rectangular features which should be excluded from symbol palette.

**Comment by harrywipperfuerth** [comment]
No, the only circular and rectangular geometries in MIL-STD 2525C are all assigned to the Fires Support Areas.

**Comment by harrywipperfuerth** [comment]
In the MIL-STD 2525D there are then, in addition to the Fire Support Coordination Measures area, circular and rectangular objects in the Target control measure symbols and Target acquisition control measure symbols areas.

**Comment by dehmer** [comment]
With #364 features currently not supported are marked accordingly in feature palette.
This issue will be addressed later with #193 and #346.
