### ISSUE TITLE
Boundaries - the Display of the echelon isn't correct

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#349]
Currently in ODIN, when displaying boundaries, the line in the area of the "echelon" is shown solid and not interrupted as is illustrated in MIL-STD 2525C and the tacticians are used to:

![grafik](https://user-images.githubusercontent.com/49548300/99392620-43c78f00-28dc-11eb-8c74-bee3e1441a4f.png)

In MIL-STD 2525C the boundaries are displayed as follows:

![grafik](https://user-images.githubusercontent.com/49548300/99397735-bbe58300-28e3-11eb-9171-616e356d12f7.png)

![grafik](https://user-images.githubusercontent.com/49548300/99397823-d91a5180-28e3-11eb-9733-d3523de67271.png)

**Comment by dehmer** [comment]
I'm not sure if there is an easy way to achieve this. But I'll try.
