### ISSUE TITLE
Missing properties for "round" infrastructure symbols

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#351]
The following icons can be created on the map, but the properties window on the right side will not open:

SIDC | Hierachy code | Description
-- | -- | --
EFFPBA----***** | EMS.INFSTR.BFI.ATM | ATM
EFFPMA----***** | EMS.INFSTR.WS.CV | Control Valve
EFFPMB----H**** | EMS.INFSTR.WS.DO | Discharge Outfall

The possible reason could be, that these three symbols are not displayed as a rectangle (like installations) but as a circle (like equipment).

**Comment by dehmer** [comment]
Currently, features are grouped in classes, which define the set of properties to display. 
One of these classes is 'EI' - EMS Infrastructure. This class contains 97 features in total.
To be able to at least edit some properties, 'EI' symbols will now be mapped to Installation properties.
As a consequence, symbols like 'Animal Feedlot' now have 'Installations properties'  as well.

<img width="461" alt="Screenshot 2021-02-24 at 08 09 15" src="https://user-images.githubusercontent.com/322462/108962236-c056d000-7678-11eb-8cb4-e2043a055a0d.png">
