### ISSUE TITLE
Symbol "Cruise Missile" isn't display on the map

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#352]
The following symbol can be selected in the map palette and dragged and dropped onto the map:

SIDC | Hierachy code | Remarks
-- | -- | --
SFAPWMCM--***** | WAR.AIRTRK.WPN.MSLIF.CM | Cruise Missile

The properties window opens, but the symbol according to MIL-STD 2525C is not displayed, only a blue dot.

**Comment by dehmer** [comment]
This is already fixed for #171 an will be included in the next release.
Commit https://github.com/syncpoint/ODIN/commit/c5db40d7d10c4d3016224843b5f36688f17c2c0b
