### ISSUE TITLE
Shortcut Alt+Strg+M for projects isn't working

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#356]
The shortcut Alt+Ctrl+M to open the project management area does not work in ODIN.

![grafik](https://user-images.githubusercontent.com/49548300/99948985-98ef1f00-2d7a-11eb-8133-3d7d4a494d73.png)

**Comment by ThomasHalwax** [comment]
I can confirm that this is an issue that is Windows related. It does not occur on OS X.
Switching to an other shortcut like ```CmdorCtrl+Alt+P``` works on Windows and OS X, too. Interestingly OS X now minimizes the electron window on ```CmdOrCtrl+Alt+M```. Seems like this is some kind of "well known" shortcut on some platforms.

My suggestion is to switch to ```CmdorCtrl+Alt+P```. @harrywipperfuerth: any objections?

**Comment by harrywipperfuerth** [comment]
From my side no objections.

Basically I am of the opinion that if a shortcut should not work (on all platforms) due to technical or "platform related" reasons, it is better in this case to do without a shortcut.

**Comment by ThomasHalwax** [comment]
closed by d5aa1cb790b2fa073280b571ce8bac9c36c03c88
