### ISSUE TITLE
Re-tagging releases

### ISSUE THREAD

**Issue by nicwortel** [syncpoint/ODIN#362]
Hi!

I noticed a couple of notifications about a v0.6.0 release in the last couple of days - it seems like you are overwriting this tag to release new changes.

Wouldn't it be better to release new patch versions (v0.6.1, v0.6.2, etc.)? That way, we can track what has changed between patch versions and I can be sure whether or not I have the latest version installed.

**Comment by ThomasHalwax** [comment]
Hi,

we are still in a pre-release stage for version 0.6.0. After releasing v0.6.0 (hopefully within the next days) we will follow the version path as you suggested.
Starting with 0.6.0 we included the electron auto-updater to make sure our users can keep their versions up-to-date.

**Comment by nicwortel** [comment]
Ok! :slightly_smiling_face: 

In that case, I would kindly suggest using pre-release labels (v0.6.0-beta.1, v0.6.0-beta.2, etc.) as per [semver](https://semver.org/), so pre-release builds can be uniquely identified and [release information](https://github.com/syncpoint/ODIN/releases) for earlier releases will not be lost.
I'm not familiar with electron auto-updater but I'm assuming it will also require unique version tags in order to determine if the user's installed version is out of date.

Either way, thanks for building this project, I'm following your work with interest!

**Comment by ThomasHalwax** [comment]
Thank you for your suggestions! You are right, electron auto-updater queries GitHub for the lastest release and notifies the user if there is a newer version available.

May I ask about your interest in ODIN? Do you have any use cases where ODIN could be helpful?

**Comment by nicwortel** [comment]
> May I ask about your interest in ODIN? Do you have any use cases where ODIN could be helpful?

I'm a software engineer with some military experience and a personal interest in military mapping and C2IS applications. I found out about ODIN because of [this tweet](https://twitter.com/spatialillusion/status/1229678069947994112) by @spatialillusions and have been following this project since then, and have been running some builds on my Linux computer to try it out.

I will send you an email to answer your questions more in-depth :wink:

**Comment by ThomasHalwax** [comment]
@nicwortel We are very happy that you like ODIN. Version 0.6.0 has been released right now and we have a lot of great things to do for the next version :-)
