### ISSUE TITLE
Ferry (Water Crossing) - TypeError: Cannot destructure property 'lat' of 'object null'

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODIN#363]
Steps to reproduce:
1. Draw a line (Water Crossing / Ferry) @ 1 : 50,000
2. Zoom out to and beyond 1 : 400,000 (or more depending on actual line length)
3. At some point the following error will be thrown: **TypeError: Cannot destructure property 'lat' of 'object null' as it is null.**
<img width="439" alt="Screenshot 2020-11-30 at 14 11 46" src="https://user-images.githubusercontent.com/322462/100614187-091b1900-3316-11eb-8943-15da96323c97.png">

**Comment by ThomasHalwax** [comment]
Looks like one of the arrows is misplaced:
<img width="337" alt="image" src="https://user-images.githubusercontent.com/38359572/100635491-e0ece380-3330-11eb-8293-6d5b13c49623.png">

**Comment by dehmer** [comment]
Hey a new NÖ-Stmk. Ferry Line :-)

Yes, there are several issue I'd like to tackle with this one:
* Remove all WGS84 calculations in favour of UTM (probably the problem above)
* Don't construct arrows and similar as line strings but as (new found) regular shapes
* Don't draw features at all under certain conditions (e.g. feature extent vs. zoom level); LoD

**Comment by dehmer** [comment]
Fixed ferry construction along with some other features:
* SEARCH AREA
* TASKS / SCREEN
* TASKS / COVER
* TASKS / GUARD
* OBSTACLE EFFECT / FIX
* CROSSING SITE / FERRY
* TASKS / FIX

<img width="457" alt="Screenshot 2020-12-02 at 11 23 18" src="https://user-images.githubusercontent.com/322462/100860844-540d6b80-3491-11eb-9c46-a2bafeb7fe2f.png">
