### ISSUE TITLE
assign external documents to a feature

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/ODIN#369]
Besides the map there are other documents like ORBAT, written orders, pictures and many others that need to be considered for the current situation. Currently the user needs to remember where those documents are located in order to open them.

I suggest that users can assign an arbitrary number of linked documents to a feature. This could be done by dropping a local document or web URL to the properties panel of the currently selected feature. The links (URIs) to the documents will be persisted. When a user selects a feature all assigned links are shown in the properties panel. By clicking on a link ODIN executes the OS _open_ command and delegates control to the operations system (finding the assigned application to the document and open it). The effect would be the same as if the user had opened the document in the filesystem explorer/finder.

Of course all CRUD operations for assigned document links (add, edit, remove link) need to be supported. Since the panel is already filled with MilStd properties we could introduce tabs to separate these concerns (feature properties from assigned documents).

**Comment by dehmer** [comment]
How would layer/project import/export be affected by this?

**Comment by ThomasHalwax** [comment]
> How would layer/project import/export be affected by this?

No external documents should be embedded into ODIN. Only the URI that points to the document should be persisted. This implies that local documents like ```/home/myUserName/Documents/some.txt``` will not be in reach for anyone but the originating user. We could think about some kind of reminder for the user, that a URI pointing to a local resource may be useless after the layer or project was exported and shared with others.
