### ISSUE TITLE
"Data source" must be displayed for the maps used

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#371]
By inserting the corresponding URL within the map administration it is possible to integrate online maps into ODIN.

In any case, the name of the "data source" is missing, when displaying the used maps. Please note that some data sources require a link to the corresponding homepage.

**Comment by ThomasHalwax** [comment]
This is called 'attribution'. It's a simple task when you have only one map to display. But with multiple maps with different opacity we need something that enumerates all enabled map sources and generates a small view that shows all corresponding attributions.
