### ISSUE TITLE
Objects are missing pattern fill within the area

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#376]
The objects listed below are currently displayed in ODIN only as "normal" area.

For some objects there is also the representation of a symbol within the area or another representation of the frame (see Remarks):

SIDC | Hierachy code | Object |  Remarks
-- | -- | -- | --
G*MPOGR---****X | TACGRP.MOBSU.OBST.GNL.ORA | obstacle restricted area |  frame with triangles
G*MPNR----****X | TACGRP.MOBSU.CBRN.RADA | radioactive area |  nuclear symbol
G*MPNB----****X | TACGRP.MOBSU.CBRN.BIOCA | biological contaminated area |  biological symbol
G*MPNC----****X | TACGRP.MOBSU.CBRN.CMLCA | chemically contaminated area |  chemical symbol
G*F-AKBI--****X | TACGRP.FSUPP.ARS.KLBOX.BLUE.IRR | kill box blue irregular |  ---
G*F-AKPI--****X | TACGRP.FSUPP.ARS.KLBOX.PURPLE.IRR | kill box purple irregular |  ---
G*GPGAY---****X | TACGRP.C2GM.GNL.ARS.LAARA | limited acces area |  ---

This also applies to the Kill Boxes Rectangular and Circular. Due to the geometry, however, this would only be considered when Issue #193 is implemented.

**Comment by dehmer** [comment]
@harrywipperfuerth Please create two separate issues for 
* Features with different frame styles (**obstacle restricted area**, but also **obstacle general zone** and similar)
* Features with missing symbols inside the area

This would be the first idea on how pattern fill could look like:

<img width="916" alt="Screenshot 2020-12-10 at 10 13 57" src="https://user-images.githubusercontent.com/322462/101751648-ca811d80-3ad0-11eb-9d98-c0c536cd4621.png">
