### ISSUE TITLE
Implementation of Offset Location Indicator (MILSTD-2525C) for single point objects

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#380]
Currently, the single point objects are displayed exactly on the point that corresponds to the coordinate on the map.

However, it can happen that the display of the single point objects can lead to a difficult or illegible situation picture.

In this case the user should have the possibility to set the Offset Location Indicator (Modifier "S" in MILSTD-2525C) to increase the legibility of the map.

**Comment by dehmer** [comment]
Offset location is one of the next things to happen, but sadly not right now.
Moving to top of backlog.
