### ISSUE TITLE
"Minimum Safe Distance Zones" can't displayed on the map

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#384]
The following symbol can't displayed on the map:

SIDC | Hierachy code | Object
-- | -- | --
G*MPNM----****X | TACGRP.MOBSU.CBRN.MSDZ | Minimum Safe Distance Zones

**Comment by dehmer** [comment]
@harrywipperfuerth Do MINIMUM SAFE DISTANCE ZONES always have 3 radii? 2525C seems to suggest this.
Are the labels '1', '2', '3' constant? There are no text modifiers for the individual circles, or are there?
In any case, we probable need a new editor/modify interaction for this.

**Comment by dehmer** [comment]
<img width="456" alt="Screenshot 2020-12-10 at 13 50 59" src="https://user-images.githubusercontent.com/322462/101775673-1b543e80-3af0-11eb-843c-f2a2a8dcaa3f.png">

**Comment by dehmer** [comment]
MIP defines MINIMUM SAFE DISTANCE as one or more stacked circles. For each radius a new circle is needed.
Maybe we can do the same. I then would suggest, that unique designation (T) is used as the circles label. The label would be placed exactly at the point, which defines the circles radius. This would allow to place labels anywhere along the circle.

As a side note: Snapping to point/line while editing/drawing would be helpful to place centres of multiple circles exactly on top  of each other.

**Comment by dehmer** [comment]
Simple/naive implementation:

<img width="605" alt="Screenshot 2020-12-10 at 14 39 20" src="https://user-images.githubusercontent.com/322462/101780788-3f674e00-3af7-11eb-95be-263c427f6595.png">
