### ISSUE TITLE
Wrong display of "Direction of Attack (Main/Supporting Attack)"

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#387]
In Odin, the objects "Direction of Attack (Aviation, Feint)" are currently displayed as two-point lines.

The objects "Direction of Attack (Main/Supporting)" are displayed as multi-point lines, as required by the users/tacticians.

In version 0.6.0, the user can click on several points on the map, but the object is displayed only from the 1st to the 2nd point (mouse click) on the map.

If the user now selects the object again, the whole line is displayed again in the "marked" mode:

![grafik](https://user-images.githubusercontent.com/49548300/102533463-becfc100-40a5-11eb-93f7-755e7f0e4f3d.png)

It becomes strange when the user creates a new point with the mouse between the first and second point and moves the line.

Now the arrow is no longer displayed at the beginning of the object, but in the middle (where the second point is now on the map):

![grafik](https://user-images.githubusercontent.com/49548300/102533933-546b5080-40a6-11eb-989a-f1d8c2c5e4b4.png)

![grafik](https://user-images.githubusercontent.com/49548300/102534006-6cdb6b00-40a6-11eb-9915-01457d9d0995.png)

**Comment by dehmer** [comment]
There are two different issues here:
A) User requests 'direction of attack' to support more than two lines, while 2525C specifies them as 2-point lines.
B) MAIN ATTACK/SUPPORTING ATTACK allow more than two point, while they should not.

**Comment by dehmer** [comment]
Fixed B).
Create new issue for A (if 2525D) supports it.
