### ISSUE TITLE
Windows focus problem

### ISSUE THREAD

**Issue by JulianKK** [syncpoint/ODIN#39]
In the settings View → Map → Filter it is possible to change the appearance of the map. This functionality gets achieved by choosing a Filter (e.g. Brightness) and then change its value by pressing an arrow key.

The problem is the fact, that the focus stays at the menubar and if you press an arrow key, you jump between the menu entries. To change the values of the Filters you first have to click in the map to pass the focus to it.

**Comment by dehmer** [comment]
Maybe related:
* https://github.com/electron/electron/issues/984
* https://github.com/electron/electron/issues/4942

**Comment by JulianKK** [comment]
In an earlier Electron version (3.x) the main window keeps the focus after menu selection.

**Comment by JulianKK** [comment]
Also in electron 4.x  it is not a problem

**Comment by dehmer** [comment]
vscode has currently scheduled Electron 4 for June 2019 (https://github.com/microsoft/vscode/pull/73119).

I think we should play it save and downgrade to Electron 3.1.9 and wait for others to do the heavy lifting. Microsoft and others surely have more power to iron out the initial issues with adoption of new Electron versions.

First tests indicate that we are compatible with Electron 3.

**Comment by dehmer** [comment]
Fixed: Downgraded Electron to version 3.1.9.
