### ISSUE TITLE
Direction of attack(s) should be displayed as mulit-point lines

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#394]
In Odin, the objects "Direction of Attack (Aviation, Feint, Main, Supporting)" are currently displayed as two-point lines.

These objects "should be displayed as multi-point lines, as required by the users/tacticians.

![Bsp Mehrpunkt für Direction of Attack](https://user-images.githubusercontent.com/49548300/107930689-98ca7e00-6f7b-11eb-8b0c-b0fa3cb80a51.PNG)

![Bsp 2 Mehrpunk für Direction of Attack](https://user-images.githubusercontent.com/49548300/107930901-e3e49100-6f7b-11eb-9ac6-7e3de26649f6.PNG)

It would also be necessary to assess whether a representation of the Echelon would be possible with the arrows.

Tacticians use this representation mainly for terrain assessment with regard to the movement possibilities of own or enemy troops.

Example:

![grafik](https://user-images.githubusercontent.com/49548300/107937584-6e30f300-6f84-11eb-9663-d4f321f28c63.png)

**Comment by dehmer** [comment]
Here we go:
Direction of Attack is now n-point, n >= 2.

<img width="584" alt="Screenshot 2021-02-23 at 18 41 51" src="https://user-images.githubusercontent.com/322462/108884425-e3e13280-7606-11eb-84f8-c5af838d2e5e.png">
