### ISSUE TITLE
Hostlity status for "One-point tactical graphic" symbols should be improved

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#396]
In Odin, almost all "One-point tactical graphic" symbols can currently only be displayed with the color black.

Exception is the representation of the hostitliy status "Hostile", because this is possible by using the modifier "N" (Hostile (Enemy)).

From the user's point of view and for the sake of clarity, the hostility status of these objects should also be displayed on the map in the same way as the colors are assigned to the respective hostility status (e.g. Friend = blue, Neutral = green, etc.).

**Comment by dehmer** [comment]
As far as I know, this is not supported in 2525C, but achievable with MilSymbols.

From left to right: friendly, hostile, neutral, unknown, "undefined"

Before:
<img width="432" alt="Screenshot 2021-02-24 at 10 18 50" src="https://user-images.githubusercontent.com/322462/108978777-44658380-768a-11eb-8c17-53ffadca16e7.png">

After:
<img width="443" alt="Screenshot 2021-02-24 at 10 19 18" src="https://user-images.githubusercontent.com/322462/108978817-51827280-768a-11eb-84cd-dd491d3f1fba.png">

**Comment by dehmer** [comment]
We will enable this for TACGRP symbols for evaluation/as an experiment.
