### ISSUE TITLE
Tool for measuring area

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#398]
To measure an area on the map, we need an easy-to-use tool for it.

While drawing, the user should be shown the total area in m² from "setting" the third point.

Whether a display from m² to km² should be changed automatically when a certain area size is "reached" (where m² display then becomes confusing) would be discussed.

After drawing the area, the total area should be visible on the map.

The area should be editable/deletable.

**Comment by ThomasHalwax** [comment]
<img width="479" alt="image" src="https://user-images.githubusercontent.com/38359572/108211717-5779d000-712d-11eb-9580-8de7d848bf95.png">
