### ISSUE TITLE
Maintenance: update outdated dependencies

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODIN#399]
Update dependencies without breaking changes.

The following dependencies have breaking changes and are addressed in separate issues:
* OpenLayers: #390 
* Electron: remote module was removed in  v11.x
* Webpack: v5.x has several changes which affect used plugins and dev-server
* electron-settings: seems to have breaking changes (main throws up)

**Comment by ThomasHalwax** [comment]
> Update dependencies without breaking changes.
> 
> The following dependencies have breaking changes and are addressed in separate issues:
> 
> * OpenLayers: #390
> * Electron: remote module was removed in  v11.x
> * Webpack: v5.x has several changes which affect used plugins and dev-server
> * electron-settings: seems to have breaking changes (main throws up)

The Electron folks did not remove the remote module in v11.x:
https://github.com/electron/electron/issues/23506#issuecomment-770425237

The [Electron Breaking-Changes Site](https://www.electronjs.org/docs/breaking-changes) says, that

> The remote module is deprecated in Electron 12, and will be removed in Electron 14. It is replaced by the @electron/remote module.

**Comment by dehmer** [comment]
@ThomasHalwax OK. But this should be addressed soon, since Electron versions increase rapidly in recent times :-)

**Comment by ThomasHalwax** [comment]
> @ThomasHalwax OK. But this should be addressed soon, since Electron versions increase rapidly in recent times :-)

True. I browsed the code and the only way we use the remote module is to
* get/set the window title
* get/set the current project path
* get the current OS in order to enable platform specific key bindings via ```mousetrap```

I think getting rid of the remote module should not be a huge problem.
