### ISSUE TITLE
Copy coordinate - Differences between ODIN and Google Maps

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#40]
Concerning #10 (closed):

If you copy a coordinate from the ODIN map (with "Alt + C") and use it to find the location in Google Maps, the location of the "marker" is not at the same location.

The differences between the locations are a few meters and several kilometers and with repeated attempts (same location in ODIN) sometimes at different locations (in Google Maps).

**Comment by harrywipperfuerth** [comment]
For example:
![ODIN copy coordinate](https://user-images.githubusercontent.com/49548300/58313512-0597ff00-7e0e-11e9-88ce-4097dbf78c83.jpg)

**Comment by dehmer** [comment]
Fixed.
