### ISSUE TITLE
Maintenance: removed unused dependencies

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODIN#400]
Remove all dependencies which are no longer used.
This will mainly include development/testing dependencies like sinon and spectron.

**Comment by dehmer** [comment]
Candidates for removal:

* spectron: already gone
* mocha-electron: currently we do not conduct Electron test
* chai, sinon: only used in one test with questionable value (management.test.js)
* enzyme enzyme-adapter-react-16: only used for serious React testing

**Comment by ThomasHalwax** [comment]
Feel free to remove "management.test.js".
