### ISSUE TITLE
inconsistent state for show/hide labels

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/ODIN#408]
Sometimes the state of the view-menu entry for 'Labels' does not match the state of the elements shown on the map. If "Labels" is checked then the labels are hidden and vice versa
<img width="473" alt="image" src="https://user-images.githubusercontent.com/38359572/112318625-8b589000-8cad-11eb-9af3-968de6490c2d.png">
<img width="461" alt="image" src="https://user-images.githubusercontent.com/38359572/112318684-990e1580-8cad-11eb-92fb-3e497f8827fb.png">

I searched the source code if the ```IPC_LABELS_TOGGLED``` signal consumed in ```main.js``` but it looks like no-one ever sends it.

**Comment by dehmer** [comment]
Label control was first introduced in commit dee2b109ff2ffc9250f61bdd3241648f04c2c702.
With new style factory the renderer part was probably canned. I will look into it.
