### ISSUE TITLE
Search for streets functionality provides poor data

### ISSUE THREAD

**Issue by JulianKK** [syncpoint/ODIN#41]
In #23 it says, that the search results of the location search are sorted by Euclidean distance, but if the the map currently shows Vienna, and you are searching for a street named “Rohrbacherstrasse” the resultlist doesn't show the corresponding nearest street. To find it, you have to search for “Rohrbacherstrasse, Vienna”

<img width="960" alt="odin" src="https://user-images.githubusercontent.com/12021125/58313702-7ccd9300-7e0e-11e9-8975-e581291adda9.PNG">
<img width="964" alt="odin2" src="https://user-images.githubusercontent.com/12021125/58313704-7ccd9300-7e0e-11e9-94fb-4545cdbdba41.PNG">

**Comment by dehmer** [comment]
That's an 'issue' with Nominatim. 'Rohrbacherstrasse' does not yield any result in Vienna.
Can't fix.
