### ISSUE TITLE
Shortcuts for Map - Filters Contrast and Grayscale inactive

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#42]
The two shortcuts 

Alt + Strg + 2 (for Contrast)
Alt + Strg + 3 (for Grayscale)

are inactive.

If you want to use it, the only possible way is about the Menue (View - Map  - Filter ...).

![ODIN Filter menue](https://user-images.githubusercontent.com/49548300/58315547-0cc10c00-7e12-11e9-9e45-437948096b49.jpg)

**Comment by dehmer** [comment]
No problem with macOS here. Will try to reproduce this with Windows 10.

**Comment by JulianKK** [comment]
I can confirm that problem with win 10. Also the reset filter functionality strg + alt + 0 does not work

**Comment by dehmer** [comment]
For me with Win 10 in VMware Fusion, only Strg+Alt+4 does not work.
I think, it's save to say, that for Windows platform, Electron menu shortcuts are a little unreliable.

**Comment by JulianKK** [comment]
the same behavior can be observed with zoom in (standard menu by electron). It is displayed as a shortcut "cntr + shift + =", but this function is called by means of "cntr + shift + +". There is an issue on the electron git repository. [#6731](https://github.com/electron/electron/issues/6731)

**Comment by harrywipperfuerth** [comment]
The shortcuts "CTRL + STRG + 2" (for "Contrast")  and "CTRL + STRG + 3" (for Grayscale) have the same "Result" (= "Contrast")!

**Comment by harrywipperfuerth** [comment]
The shortcuts "CTRL + STRG + 2" (for "Contrast")  and "CTRL + STRG + 3" (for Grayscale) have the same "Result" (= "Contrast")!

**Comment by JulianKK** [comment]
Not in my version ???

**Comment by JulianKK** [comment]
Sorry, you're right, there was something wrong with the merge of the pullrequests

**Comment by dehmer** [comment]
Sorry guys! My bad! 
@JulianKK Thanks for fixing!
@harrywipperfuerth Thanks for spotting! And could you please close the issue after you verified the fix?

**Comment by harrywipperfuerth** [comment]
Sorry guys, it's not working.

If you select Map - Filter - Grayscale, "Contrast" appears on the map again (is the same problem as with shortcuts!).

The problem is unsolved from my point of view.

**Comment by dehmer** [comment]
@harrywipperfuerth 
Hmm, maybe your project is not up to date (and cannot be updated). Please run the following commands and attach the complete conversation (command results) from your command line terminal to this issue.

`
git status
git pull
git checkout develop
npm run webpack
npm start
`

**Comment by harrywipperfuerth** [comment]
git status:

$ git status                                                                     On branch develop                                                                Your branch is up to date with 'origin/develop'.                                                                                                                  Changes not staged for commit:                                                     (use "git add ..." to update what will be committed)                       (use "git checkout -- ..." to discard changes in working directory)                                                                                               modified:   package-lock.json                                                                                                                             no changes added to commit (use "git add" and/or "git commit -a")
--


git pull:


$ git pull                                                                       remote: Enumerating objects: 194, done.                                          remote: Counting objects: 100% (175/175), done.                                  remote: Compressing objects: 100% (56/56), done.                                 Receremote: Total 133 (delta 83), reused 125 (delta 75), pack-reused 0           Receiving objects: 100% (133/133), 20.39 KiB \| 254.00 KiB/s, done.               Resolving deltas: 100% (83/83), completed with 28 local objects.                 From https://github.com/syncpoint/ODIN                                              eecb148..f56eb88  develop          -> origin/develop                             f652c2f..2733edc  experimental/poi -> origin/experimental/poi                 error: Your local changes to the following files would be overwritten by merge:          package-lock.json                                                        Please commit your changes or stash them before you merge.                       Aborting                                                                         Updating eecb148..f56eb88
--


git checkout develop:


$ git checkout develop                                                           Already on 'develop'                                                             M       package-lock.json                                                        Your branch is behind 'origin/develop' by 7 commits, and can be fast-forwarded.    (use "git pull" to update your local branch)
--


npm run webpack:


$ npm run webpack                                                                                                                                                 > odin-c2is@0.2.2 webpack E:\01_Syncpoint\11_ODIN                                > webpack
--


npm start:


$ npm start                                                                                                                                                       > odin-c2is@0.2.2 start E:\01_Syncpoint\11_ODIN                                  > electron . --noDevServer
--

**Comment by dehmer** [comment]
OK, you cannot pull the latest version, because a local file (package-lock.json) has changed in the meantime. __That's not your fault!__ 
`npm install` may update this file when new dependency versions are detected and installed.

To fix this temporarily, type:

    git checkout package-lock.json

and try again. This time omitting `npm install`.

Whenever you so something like

    Changes not staged for commit: (...)

when running `git status` or for `git pull`

    error: Your local changes to the following files would be overwritten by merge: (...)

chances are that an update does not work. I'm very sorry for the inconvenience. We are working on a solution to supply you with the latest snapshot builds.

Thanks for your patience! 👏 👏 👏

**Comment by harrywipperfuerth** [comment]
After deleting ODIN and starting it via the release version, it runs correctly.
I will complete this issue as solved.
