### ISSUE TITLE
Copy coordinates to system/OS clipboard

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/ODIN#433]
In order to describe the current situation textually (e.g. in a report or an order), I want to copy the coordinates of a symbol or the coordinates of the current location of the mouse pointer to the __system__/__OS__ clipboard. The coordinates should use the MGRS notation.

By pressing a keyboard shortcut (i.e. CMDorCTRL + C) the following should happen:

1) _no feature_ selected: the position of the current mouse pointer on the map should be used
2) a feature with geometry _point_ is selected: the position of the feature should be used
3) a feature with geometry _line_ or _polygon_ is selected: an array of coordinates should be used
4) a feature with a _complex geometry_ (corridor, fan area): no coordinates shroud be used since it may not be clear for the user which coordinates represent which geometry of the resulting symbol.

**Comment by csingewald** [comment]
The selected keyboard shortcut is CMDorCTRL+D
