### ISSUE TITLE
Symbols "CFL" and "PL" only displayed as a normal line

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#435]
The symbols "CFL" and "PL" are displayed on the map only as a normal line without the text label.

The designation for the lines is displayed only after a text entry in the "Unique Designation" field.

However, for the lines "NFL" and "FSCL", which are to be treated in the same way, the designation is already displayed on the map during creation.

**Comment by ThomasHalwax** [comment]
So the desired behavior should be:

* show 'PL' or 'CFL' if there is no unique designation
* show 'PL + UD* or 'CFL + UD' if there IS a UD

@harrywipperfuerth Please check behavior implemented in branch fix/435
