### ISSUE TITLE
POI: user experience (UX)

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODIN#46]
Let's say we want to maintain a general list of points-of-interest, which is not necessarily limited to tactical requirements. We want to
* create new POIs with name (id) and position
* rename and move POIs
* delete POIs
* add/change POI comments and tags
* Find/delete POIs in Spotlight

<img width="983" alt="Screen Shot 2019-05-26 at 08 05 57" src="https://user-images.githubusercontent.com/322462/58378119-59315680-7f8e-11e9-9749-837c6c87b151.png">

All this requires quite some user interaction. We should collect ideas and thoughts on how to design UX and user interaction for such features, which later can be applied to the more general case of tactical symbols.

**Comment by dehmer** [comment]
I created an [experimental branch](/syncpoint/ODIN/tree/experimental/poi) to play with some basic POI functions:
* POI is automatically created when the result of a reverse coordinate search is displayed in the map
* POI marker is displayed in map (with current position)
* POIs are included in Spotlight search
* POIs can be delete from Spotlight
* POI marker can be moved, position is updated accordingly
* POIs are stored (leveldb, event sourced)

**Comment by dehmer** [comment]
<img width="977" alt="Screen Shot 2019-05-26 at 11 21 14" src="https://user-images.githubusercontent.com/322462/58379762-7115d400-7fa8-11e9-9b72-3ca4efb7d8f4.png">

* on click (marker): highlight selected marker 
* on click (map): deselect (if any)
* move marker (either selected or not), select/highlight after move
* highlight newly added marker
* Keyboard (DELETE/CMD+BACKSPACE): remove POI for selected marker from store and map

**Comment by dehmer** [comment]
Property pane will receive controls to edit name/id, comment and position (including pick position from map).

<img width="976" alt="Screen Shot 2019-05-26 at 16 02 07" src="https://user-images.githubusercontent.com/322462/58382861-b13c7d00-7fcf-11e9-9cbb-3db24757093f.png">

**Comment by ThomasHalwax** [comment]
What is the exact flow of commands in order to create a POI? I can't manage to create a POI marker.

**Comment by dehmer** [comment]
@ThomasHalwax Yeah, that's still pretty strange...

1. Coordinate format should be UTM or MRGS
2. Pick/copy a coordinate (Option-C), 
3. Spotlight search for this coordinate (Command-F)
4. Pick single result from list
5. POI is automatically created

**Comment by dehmer** [comment]
We have a first implementation which is not too shabby.
Improvements are to be reported as new issues.
