### ISSUE TITLE
WMS with credentials

### ISSUE THREAD

**Issue by sasm2m** [syncpoint/ODIN#498]
In the WMS URL include the possibility to authenticate for a layer with restrictions

**Comment by ThomasHalwax** [comment]
@sasm2m would basic authentication be sufficient for the first shot?

**Comment by sasm2m** [comment]
yes, validation based on url of the type: http://<user>:<password>@urlwms/ would be enough

**Comment by sasm2m** [comment]
yes, validation based on url of the type: http://user:pass@urlwms/ would be enough

**Comment by ThomasHalwax** [comment]
@sasm2m We do have a prototype where we transfer `http://user:pass@some.host/path` into `http://some.host/path` and move `user:pass` into the `Authorization` header.

Are you aware of a server where I can test the implementation?

**Comment by ThomasHalwax** [comment]
@sasm2m http 401 says "Auth Required". Is there a chance that you can provide temporary credentials for the WMS server?

**Comment by sasm2m** [comment]
Sure, https://btom_jg:870m_j6@www.geoportaligm.gob.ec/bgom/btom_jg/ows?service=wms&version=1.3.0&request=GetCapabilities

**Comment by ThomasHalwax** [comment]
@sasm2m Thanks! I fixed the error and now I can see 67 layers. I tried a few but they seem to return transparent png tiles only.

**Comment by ThomasHalwax** [comment]
@sasm2m Looks like I found some non-transparent tiles :-)
<img width="1707" alt="image" src="https://user-images.githubusercontent.com/38359572/177186330-50faa4de-c1ab-4e77-b979-a3aa1c51bac4.png">

**Comment by sasm2m** [comment]
Great job, if it works, it already depends on the wms layers that are shared with the use of the username and password. We would be about to close the issue
