### ISSUE TITLE
Choose map scale (directly)

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODIN#5]
Users might want to directly choose a standard scale (e.g. 1:50.000, 1:25.000).

This poses at least two problems

* Web Mercator distortion (see also #4)
* Leaflet zoom factor does not align to 'even' scales, e.g. closest to 1:50.000 is 1:35000

Compare [OSM zoom levels](https://wiki.openstreetmap.org/wiki/Zoom_levels)

**Comment by ThomasHalwax** [comment]
I don't think choosing a scale on a digital output device makes any sense so I close this issue.
