### ISSUE TITLE
Fullscreen: auto hide application menu (Windows only)

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODIN#56]
In fullscreen mode for Windows platform, it would be nice to automatically hide the menu bar.

Electron seems to support some options to this regard:
BrowserWindow option `autoHideMenuBar` and https://electronjs.org/docs/api/browser-window#winsetautohidemenubarhide

**Comment by JulianKK** [comment]
The visibility of the menu bar in fullscreenmode can now be toggled by pressing the Alt key
By default, visibility is false
see pullrequest [#57](https://github.com/syncpoint/ODIN/pull/57)
