### ISSUE TITLE
Copy Coordinate 

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#76]
The function "Copy coordinate (ALT+ C)" remains permanently active if the following procedure is selected:

1) Press "ALT + C" (without picking a coordinate from the map)
2) Press "STRG + F" (for the function "Find")

Afterwards the mouse pointer remains marked as a "crosshair" and no coordinate can be selected on the map.

**Comment by dehmer** [comment]
Confirmed as an issue.

**Comment by dehmer** [comment]
fixed.
