### ISSUE TITLE
Change map display brightness

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODIN#8]
The user should be able to dim map brightness.
NOTE: Only the raster layer is affected, when the brightness is changed.

**Discussion**: Why would a user want to do this?

100% brightness:
<img width="835" alt="Screenshot 2019-04-13 at 08 51 19" src="https://user-images.githubusercontent.com/322462/56075885-d3848d80-5dc9-11e9-8836-9049fc550b15.png">

60% brightness:
<img width="835" alt="Screenshot 2019-04-13 at 08 51 36" src="https://user-images.githubusercontent.com/322462/56075889-de3f2280-5dc9-11e9-8213-890bcfccc669.png">

**Comment by dehmer** [comment]
**Experimental**: Play with other filter effects
* Contrast
* Grayscale
* Hue
* Invert
* Sepia

<img width="835" alt="Screenshot 2019-04-13 at 09 01 43" src="https://user-images.githubusercontent.com/322462/56075952-de8bed80-5dca-11e9-842f-9c1231d31710.png">

**Discussion**: Is there any use case for this?

**Comment by harrywipperfuerth** [comment]
The reason for this is, that the user can more easily "read" the symbols / objects on the map (especially if the quality of the map (e.g., dark mushy colors) is not so good).

**Comment by dehmer** [comment]
I see. But if the amplifiers (or better text modifiers for APP6-C) were crisp and clear and easily readable, dimming would not be required. I guess we have to put in quite some effort and extensive testing concerning readability of symbols and their surrounding text modifiers. 

This reminds me to create an issue to altogether 'turn off' the raster map background.

From a technical perspective, we hold on to this functionality, in order to learn more about Electron and how to design the internal architecture (specifically storing/restoring user settings).
