### ISSUE TITLE
"File - Exit" has the same function as "Window - Close"

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#85]
The function "File - Exit" has the same behavior as the function "Window - Close" (CTRL-W).

I suggest that only the function "File - Exit" should close ODIN, so the function "Window - Close" would not be necessary.

**Comment by dehmer** [comment]
That is not necessarily correct.
Once multiple windows (maps or others), 'Window - Close' will only close the focused window, but 'File - Exit' will close the application entirely.

But for now it looks like it's the same, though.
