### ISSUE TITLE
Spotlight: Navigation with arrow keys

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODIN#91]
* Pressing cursor/arrow down in search field should select first entry in list.
* Pressing cursor/arrow up when first entry is selected should do nothing.
* Spotlight list/entries should be navigable with cursor/arrow keys.
* Selected entry should be highlighted.
* Deleting the selected entry should select entry above/below.
* Remaining functionalities must not be changed.

**Comment by JulianKK** [comment]
I had to adjust the key assignment due to ambiguity. This results in the following keyboard shortcuts:

Enter: Activate and close
Cmd / Cntr + Down Arrow: Activate
Cmd / Cntr + Backspace or Delete: delete entry

**Comment by dehmer** [comment]
done.
