### ISSUE TITLE
Illogical object selection after fade-in/out layer

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#95]
The following procedure applies to an illogical display of selected objects from imported layers.

1) Press CTRL-F (Find) to open the properties display.
2) Select an unit of the imported layer (search display must be visible).
3) Hide Layer
4) Show Layer
5) Display of several objects as marked objects (always in different display/composition)

![grafik](https://user-images.githubusercontent.com/49548300/62324229-56307600-b4a9-11e9-9008-12fa4e864a70.png)

**Comment by harrywipperfuerth** [comment]
This happens by equipments too

![grafik](https://user-images.githubusercontent.com/49548300/62325168-60537400-b4ab-11e9-895e-bde17c74031d.png)

**Comment by dehmer** [comment]
fixed.
