### ISSUE TITLE
Not possible do delete objects from map or bookmarks/layers from the "Find"-list

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#98]
Now it is no longer possible to delete bookmarks or layers from the "Find" list (you cannot select or delete them).

It is also not possible to delete individual objects from the map (neither with "Delete" in the "Edit" menu nor with the "Delete" button on the keyboard).

**Comment by dehmer** [comment]
We had to change the key mappings. 
Could you try CTRL+DEL and CTRL+BACKSPACE to delete items in Spotlight.

**Comment by harrywipperfuerth** [comment]
With CTRL + DEL the deletion from the search list is possible. It is not possible to delete individual objects from the map yet.

**Comment by dehmer** [comment]
Bound CTRL+BACKSPACE to delete action (for Windows platform).
