### ISSUE TITLE
Echelon and Hostility Status not working yet (NAI, TAI, most TG)

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#99]
Echelon and hostility status do not work with the following objects on the map:

- NAI
- TAI
- AA
- AO
- OBJ

In addition to the status hostile, the selection of neutral (green), unknown (yellow, maybe orange for easier recognizability) and civilian (purple) should also be taken into account in this area (according to MIL-STD-2525C, TABLE XIII - color range values for filled symbols).

According to APP6 (C), black (symbols for some control measures (e.g. area, lines, boundaries, etc.), green (for obstacles) and yellow (for chemical, biological, radiological, nuclear (CBRN) contaminated landfill) are also used in this area (see Chapter 1, pages 11 and 16).

**Comment by dehmer** [comment]
Yes, this issue is rather urgent.
Also 'anticipated/planned' won't show as dashed lines.

**Comment by dehmer** [comment]
done.
